nvm.sh
test/fast/Unit tests/nvm_ls_current

use `command which` to ignore zsh's buildin command `which`.
zsh's `which` will not return the path to node if someone create a alias like `alias node="node --harmony"`.

Fix which command in zsh (#604).

---

nvm.sh
test/fast/Listing versions/Running "nvm ls node_" should return a nonzero exit code when not found
test/fast/Listing versions/Running "nvm ls" should display all installed versions.
test/fast/Unit tests/nvm_add_iojs_prefix
test/fast/Unit tests/nvm_ensure_version_prefix
test/fast/Unit tests/nvm_has_system_iojs
test/fast/Unit tests/nvm_iojs_prefix
test/fast/Unit tests/nvm_is_iojs_version
test/fast/Unit tests/nvm_ls_remote_iojs
test/fast/Unit tests/nvm_node_prefix
test/fast/Unit tests/nvm_remote_version
test/fast/Unit tests/nvm_strip_iojs_prefix
test/fast/Unit tests/nvm_strip_path
test/fast/Unit tests/nvm_version
test/fast/Unit tests/nvm_version_dir
test/fast/Unit tests/nvm_version_path
test/installation/io.js/install already installed uses it
test/installation/io.js/install from binary
test/installation/io.js/install two versions and use the latest one
test/installation/io.js/install version specified in .nvmrc from binary
test/installation/io.js/install while reinstalling packages
test/installation/io.js/setup_dir
test/installation/io.js/teardown_dir
test/slow/node 0.6.21 should install 0.6.21-pre
test/slow/nvm use/Running "nvm use iojs" uses latest io.js version
test/slow/nvm use/Running "nvm use node" uses latest stable node version
test/slow/nvm use/setup_dir
test/slow/nvm use/teardown_dir

This branch adds support for https://github.com/iojs/io.js / https://iojs.org/
The following features should now work:
- `nvm install iojs` will install the latest `io.js` version. `nvm ls iojs` and `nvm use iojs` will function as you'd expect.
- `nvm install node` will install the latest stable `node` version. `nvm ls node` and `nvm use node` will function as you'd expect.
- In general, a specific `io.js` version can be referenced with the "iojs-" prefix. If `node` were to ever release a `v1.0.0`, `v1.0.0` would refer to `node`, and `iojs-v1.0.0` would refer to `io.js`. In the near future, `node-v1.0.0` will also refer to `node` unambiguously. This applies to all `nvm` commands, including working with aliases and `.nvmrc` files.
- `io.js`, unlike `node`, does not have a SunOS binary. …

`io.js` support

---

README.markdown

Refs: #303 #579
Just a blurb to mention the two current solutions for fish users. I wasn't sure where, so I opted to put it at the end in the "Problems" section as a default, but we might want to mention it higher up (e.g. in the "Install" section).

Point fish users in the right direction

---

.travis.yml
install.sh
test/install_script/nvm_check_global_modules

----
When you install `nvm`, if you have any `npm` modules installed globally (with `-g`), they'll no longer be linked to the current install of Node and `npm`, nor is uninstalling them unintuitive.
Notifying the user of this fact seems like good practice.

Notify the user that they're losing access to global modules

---

nvm.sh

Fixed the download url for raspberry pi related `armv6l` and `armv7l` for iojs. I could only test for `armv6l` as I don't have a Raspberry PI 2, but the the url should be correct for [iojs v1.3.0](https://iojs.org/dist/v1.3.0/) and below. 
The latest iojs version don't have the build the `armv6l`, but i'm guessing it's in progress. I think we can check with @rvagg on whether `armv6l` builds will be available for future versions of iojs.
Thanks :smile:

fix: download url for iojs armv6l and armv7l. #678 #227

---

install.sh

When used with a privisioning system that monitors exit status, updating from git fails on line 72:
`cd "$NVM_DIR" && command git checkout --quiet $(nvm_latest_version) && command git branch --quiet -D master >/dev/null 2>&1`
This is because `master` doesn't exist.
This patch checks for the existance of `master` before deleting the branch.

- fixed return code of 1 when updating from git

---

nvm.sh

Sourcing `nvm.sh` in version `0.24.0` results in the following message being output to stderr:
ls: yes: No such file or directory
This is caused by `nvm_supports_source_options`, which fails (as it should apparently) in my environment. While the failing is expected, the error message doesn't seem so, and I personally find it a bit nagging to always see that message when starting a new shell session.
The fix in this PR is very simple, and it doesn't seem to break any test.

Fix error message when sourcing nvm.sh

---

nvm.sh

Some patterns contained a no-op `*`; the `*` would match the empty string
because # or % replacement (unlike ## or %%) tries to find the shortest match.
(Follow up to #709.)

Consolidate and avoid sed/cut calls, clean up pattern matches

---

nvm.sh
test/fast/Running "nvm use system" should work as expected

When running nvm use, successful changing of versions lists the new node version.  The npm version may also be switched, but this is not listed.
This commit updates nvm to display the npm version that was switched to alongside the node version

Include npm version when displaying results of switch.

---

README.markdown

Using `.` and not `source`, since it's more portable
cf. #704 and https://wiki.ubuntu.com/DashAsBinSh#source

Remove source bashism

---

nvm.sh

I have no idea how to write tests for this. I have about 3hrs of linux/RPi experience, but I know that my Raspberry Pi 2 reports an architecture of armv7l whereas nvm currently only detects armv6l as a Raspberry Pi. I made this change on my machine and it worked, so I am contributing my changes. :-) Hopefully they help.
If you want to give me a little direction on how to write and run tests I can try to help out with that also. :-)

adding architecture detection for Raspberry Pi 2

---

nvm.sh
test/installation/node/install from source without V8 snapshot for ARM

At the time of this writing, there is a problem with the Google V8 Snapshot feature causing node to segmentation fault on ARM devices. Snapshotting helps node start faster and is not a big-deal feature so it's safe to disable by default for ARM.

Add --without-snapshot configure flag to ARM devices by default

---

nvm.sh
test/fast/Running "nvm use foo" where "foo" is circular aborts
test/fast/Running "nvm use iojs" uses latest io.js version
test/fast/Running "nvm use system" should work as expected
test/slow/nvm use/Running "nvm use iojs" uses latest io.js version
test/slow/nvm use/Running "nvm use node" uses latest stable node version
test/slow/nvm use/Running "nvm use v1.0.0" uses iojs-v1.0.0 iojs version

When sourcing nvm.sh, a considerable amount of time is spent running npm --version only for that output to be black-holed to /dev/null

Adding --silent option for nvm use, and using it to disable processing certain output to speed up shell startup

---

install.sh

Fixes #775. After everything is installed, instead of restarting the terminal, just load the nvm.sh file. :sparkle:

Source the nvm.sh file

---

install.sh
test/install_script/nvm_detect_profile

As per commit message.
I am using zsh on Ubuntu, but I am keeping also the default `.bashrc` that gets shipped with Ubuntu in my home folder. As of now, the nvm "loading" configuration gets added to `$HOME/.bashrc` because the check on `.bashrc` is encountered before the check on `.zshrc`.
`basename` is part of the GNU coreutils so it should be widely available and this should work also on other OSes.
(`sh` is `dash` on my system)
```
[~/extra/nvm/nvm]$ cat ./install.sh | sh
=> Downloading nvm from git to '/home/cristian/.nvm'
=> Cloning into '/home/cristian/.nvm'...
remote: Counting objects: 3693, done.
remote: Total 3693 (delta 0), reused 0 (delta 0), pack-reused 3693
Receiving objects: 100% (3693/3693), 827.00 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2132/2132), done.
Checking …
```

Detect shell type from $SHELL variable instead of .$SHELLrc files

---

README.markdown

I wanted to add the syntax and example usage for the --reinstall-packages-from when migrating packages to a new Node install to the Readme file.

Updated readme file to include --reinstall-packages-from

---

nvm.sh

@reybango added docs for this switch in the readme in #795. I attempted to add similar info in the `nvm help` usage output. Currently there's no clear format for documenting command switches in this help output (there's another, `--copy-packages-from` that I didn't add info for). If the style I used here is not acceptable that's fine, it can just be a starting point for discussion of how to doc some of these undocumented switches. :palm_tree:

Add usage string for --reinstall-packages-from

---

README.markdown

Correct usage of the [neither-nor](https://en.wiktionary.org/wiki/neither) construction.

Use neither in README

---

README.markdown

Both are no longer maintained, both now link to [bass](https://github.com/edc/bass).

Replace links to nvm-fish and nvm-fish-wrapper with a link to bass

---

nvm.sh
test/fast/Unit tests/nvm_supports_xz
test/fast/teardown

Saves us ~25% bandwidth, but only nodejs 4.0.0 and forward. We check for the existence of `xz` so older versions or targets without it is unaffected.

Support `xz` tarballs if available

---

README.markdown

Note compatibility issue with `set -e`

---

README.markdown

Includes a reference to `nvm` plugin for Oh My Fish framework.

README: Add link to a dedicated nvm wrapper for fish shell

---

nvm-exec
test/slow/nvm exec/Running "nvm exec 0.x" should work

Fix the below problem:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~bash
$ nvm exec bash -c 'echo foo bar'
$
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix `nvm-exec` for the commands includes white-spaces

---

nvm.sh
test/installation/node/install from source with thread parameter

Should build parallelly to make the whole process faster.

Enable multiple jobs for make when build from source

---

install.sh

When I run install.sh on OS X as a user with a space in my name,
I expect the script to complete without errors.
Instead two errors are thrown and the profile cannot be found.
```
bash: line 134: [: /Users/dave: binary operator expected
bash: line 148: [: /Users/dave: binary operator expected
=> Profile not found. Tried  (as defined in $PROFILE), ~/.bashrc, ~/.bash_profile, ~/.zshrc, and ~/.profile.
```

install.sh - quote $DETECTED_PROFILE

---

install.sh
test/install_script/nvm_detect_profile

I just rebased david’s patch and applied your comments.
Let me know if there are any other changes that are needed to accept this. 
Thank you!

Fix profile var

---

nvm.sh

This PR adds support for sha256 checksums for io.js and node.js.

Added support for sha256 checksums

---

install.sh
nvm-exec
test/fast/Running "nvm use x" should create and change the "current" symlink
test/fast/Running "nvm use x" should not create the "current" symlink if $NVM_SYMLINK_CURRENT is false

My bash is not installed in /bin/bash.

use env bash rather than /bin/bash

---

nvm.sh
test/fast/Sourcing nvm.sh should not modify parameters of caller

When sourcing a script without parameters in zsh the sourced scripts
gets the same parameters as the sourcing file and is able to modify
these parameters. Prevent nvm from removing all parameters of sourcing
script by processing a copy of the parameters in a function.

Do not modify parameters of sourcing script in zsh

---

README.markdown

Just a note/fix for a hiccup I ran into installing from the script file on OS X [Yosemite]. Go figure, I somehow didn't have a .bash_profile file on this machine yet.
(Solution originally [found on Stack Overflow](http://stackoverflow.com/a/30031102/48700), where I added similar steps for future visitors.)

Added note about OSX's missing .bash_profile file.

---

nvm.sh
test/fast/Running "nvm deactivate" should unset the nvm environment variables.

I would like to know if my current shell are using a node configured by the nvm.
But the are only 3 cheap ways to know
- check if there are the nvm directory on PATH
- check the version using the NVM_BIN or NVM_PATH
Using the NVM_BIN is very simple. Using this simple function:
```bash
function __node_ps1() {
if [[ ! -z "$NVM_BIN" ]]; then
local array=(${NVM_BIN//// })
local version=${array[-2]}
echo " js(${version##*v})"
fi
}
```
But after a `nvm deactivate` or `nvm use system` the nvm keep these environment variables.

Unset NVM_BIN when is not necessary

---

nvm.sh
test/fast/Running "nvm uninstall" with incorrect file permissions fails nicely
test/slow/nvm uninstall/Running "nvm uninstall 0.12.6" uninstalls v0.12.6
test/slow/nvm uninstall/Running "nvm uninstall" with incorrect file permissions fails nicely
test/slow/nvm uninstall/setup_dir
test/slow/nvm uninstall/teardown_dir

Fixes https://github.com/creationix/nvm/issues/840

Check installation dir permissions before uninstalling

---

README.markdown

On updating `nvm` using the manual instructions, I noticed the tags weren't getting pulled in so I ended up on the same version.
Steps to reproduce:
Run the manual update line in `README.markdown`
What do you expect:
To end up on the most recent version of `nvm`
What happens:
You end up on the same version of `nvm`
On older versions of git this change will only pull tags (as opposed to tags and branches), but given it's part of a chain of commands that only use tags, I think that's ok?
Thanks for the great library.

Explicitly fetch tags in the manual update

---

.travis.yml

Since the tests don't rely on / [fall into](https://github.com/creationix/nvm/commit/47bbf93f5003cc695e572d2fd572c13a4ac879e5) any of the [language categories](https://docs.travis-ci.com/user/languages/) defined by Travis CI, [`language: generic`](https://github.com/travis-ci/travis-ci/issues/4895#issuecomment-150703192) can be used.

Use `language: generic` in `.travis.yml`

---

README.markdown

Minor changes:
* Fixed: brand name references to "XCode" that should be "Xcode". (source: https://developer.apple.com/xcode/)
* Fixed: brand name references to "OSX" that should be "OS X". (source: http://www.apple.com/osx/)

Update README.markdown with some stylistic changes

---

nvm.sh

Currently, using the `nvm.sh` script from another script where the check for unbound variables is on (`set -u`) will give the following error:
```
NVM_USE_OUTPUT: unbound variable
```
The issue described above occurs on an Ubuntu 14-04 environment Bash version 4.3.11.
However, it didn't occur on my MacBook Pro (v10.11.4) with Bash version 3.2.57.

Fix is variable set test

---

README.markdown

Add info WRT installing on Alpine Linux / Busybox

---

nvm.sh

To install nodejs on aarch64 architecture you need to use arm64 packages. I just added new  case to set correct $HOST_ARCH in this case.

Use arm64 packages on aarch64

---

install.sh
test/install_script/nvm_install_dir

After the PR:
* Uses a function to define the install dir (aka `NVM_DIR`)
* Does not replace an empty yet defined `NVM_DIR` variable, but uses a default value instead
* `NVM_DIR` is used at a single point in the install script

[install script] Refactors NVM_DIR

---

nvm.sh

Use `case` instead of multiple `if`/`else` statement.

[refactor] use "case" instead of if/else in install

---

install.sh

return to the previous directory after fetching/updating nvm

---

nvm.sh
test/fast/Unit tests/nvm_ensure_version_installed
test/slow/nvm run/Running "nvm run 0.x" should error out sensibly when 0.x is not installed

`nvm use`, `nvm run` and others check if the version is installed before executing Node, but the error message could be clearer on what steps the user has to take to achieve what they want, this makes that clearer by telling the user which commands they need to run.

Improve error messages for missing versions

---

install.sh

Fixes #1146 by grouping the commands that handle the error.
I also removed a subshell wrapper from a similar set of lines right above. It looks to me like that is no longer necessary.
Please advise on testing you'd like me to run or include. I'm in the process of verifying on bash 4.3.

Install should not exit after successful git clone

---

README.markdown

Ensure `git describe` gives latest tag
I recently ran the upgrade instructions and I ended up with the version
I was already on. This happened because `git describe` describes a
commit using the most recent tag reachable from it. Since I already had
a tag checked out, it was describing the tag I had already checked out.
Thankfully, `git describe` accepts an optional commit-ish, which it will
use instead of what we have currently checked out. Testing this in my
terminal now gives me the latest tag on origin, which is what I am
interested in when updating to the latest version.
```
~/.nvm ❯❯❯ git describe --abbrev=0 --tags
v0.30.1
~/.nvm ❯❯❯ git describe --abbrev=0 --tags origin
v0.31.3
```
I also added it to the manual install instructions for consistency and
extra safety.
---
Ensure `git …

Improve installation and upgrade instructions

---

README.markdown

git-describe was taught `--abbrev=0` in 1.5.0:
https://github.com/git/git/blob/master/Documentation/RelNotes/1.5.0.txt
git-describe was taught `--match` in 1.5.5:
https://github.com/git/git/blob/master/Documentation/RelNotes/1.5.5.txt
I don't see anything else potentially weird in here, so I think it is
safe to proclaim that the minimum git version required to run these
commands is 1.5.5.
Documenting this minimum version required here should help people debug
possible issues and help maintainers of this project understand the
impacts of modifying these commands in the future.

Document required git version

---

install.sh

Line 302/301 `printf "$SOURCE_STR"` is missing a trailing newline char,
while line 281/282 and 285/286 have their own new line char, so I  just
remove the manually added newline char, and add it to the end of the
variable "$SOURCE_STR", so no more manually newline char needed there.

Add trailing newline char to $SOURCE_STR

---

install.sh

Revert %s-formatting for SOURCE_STR when writing to shell profile

---

.travis.yml
install.sh

Run `shellcheck` on tests to ensure we're not following bad practices.
Note that once this build completes, successive shellcheck builds will be much faster due to travis caching.

[Tests] add `shellcheck`

---

README.markdown

If you go to the [fin repo](https://github.com/fisherman/fin) you'll see that it isn't a node version manager, but simply a plugin manager for Fish. Seems out of scope for the readme, and there are other plugin solutions for fish as well. I suggest removing the reference.

Removes fin from the readme

---

.travis.yml

Consolidate APT packages definition into one place, so that the folding is displayed correctly.

Consolidate APT packages

---

README.markdown

This pull request resolve two questions:
1. For example, my project path is /home/user/work/nvm, in this project directory there is a .nvmrc file with v4.4.7, and my nvm default is v6.7.0。if i enter /home/user/work/nvm, nvm change node to v4.4.7 which is reasonable. but if i enter /home/user/work/nvm/public, nvm use default invoked and now the node become v6.7.0. use the new code, when enter /home/user/work/nvm/public, nvm not only check if .nvmrc exist in this directory, bus also check parents directory which can solve my problem.
2. In current version of nvm, if my node version is v6.7.0 and the directory i enterd have .nvmrc file with content of v6.7.0, nvm also invoke nvm use and cost some time, it's meanless.

speed up when change directory in zsh

---

nvm.sh
test/installation_node/install hook

For user experience enhancement/improvement
before:
```
$ nvm i 7
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v7.0.0 (npm v3.10.8)
$ nvm i 5
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v5.12.0 (npm v3.8.6)
```
after:
```
$ nvm i 7
Start to download and install node v7.0.0
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v7.0.0 (npm v3.10.8)
$ nvm i 5
Start to download and install node v5.12.0
######################################################################## 100.0%
Computing …
```

[New] Print the version is going to be installed

---

nvm.sh

Currently AIX isn't supported in nvm so I have made a few small changes to make this work:
-Change tar to gtar for AIX
-Change make to gmake for AIX
-Set ARCH as ppc64 for AIX

Add AIX support

---

nvm.sh

- Delete broken/checksum not matched local cache
- More output message.

Improve nvm_download_artifact() process, fix #1291

---

install.sh

This reverts commit ce7f6d6e5287fade16c41c7a18dd3a2043928efe.
ce7f6d6e5287fade16c41c7a18dd3a2043928efe could be a mistake, as we'll always execute the gc command at the end of `install_nvm_from_git()`, this commit should be reverted, sorry for my mistake.

Revert "Also run git gc after nvm upgraded"

---

nvm.sh

This will help speed up the installation time for the install from source and non-first time
installation as `make` can use the "cache", this can speed up the build time and test time on
Travis-CI as we'll cache .cache dir.
Ref:
```
$ time nvm i -s 6.9.1
.
.
.
Now using node v6.9.1 (npm v3.10.8)
real    0m31.914s
user    0m28.116s
sys     0m4.344s
```

Do not remove src dir after compilation

---

nvm.sh

[Fix] `nvm install`: Handle 'N/A' version instead of asking to install it

---

.travis.yml
nvm.sh
test/fast/Unit tests/nvm_clang_version

[New] Use Clang as C/C++ compiler if we detected it, close #902

---

.travis.yml

- Use Travis CI apt addon source whitelist to load apt source
- Use Travis CI apt addon to install additional packages
This can make `.travis.yml` more structured and cleaner, prevent duplicating apt package list update and dependencies calculation which means it can speed up the CI build.

Optimize package install process on Travis CI

---

.travis.yml

The works in #1310 are huge and need time, since the current clang in Travis CI is not working yet, should remove this part until we refactor the testing work flow.

[Tests] Remove not working clang part until we refactor the workflow

---

.travis.yml

Just found that only caching `$HOME/.cabal` is not enough, also need `$HOME/.ghc`
See the result at:
https://travis-ci.org/PeterDaveHelloKitchen/nvm/builds/178875370

[Tests] also cache $HOME/.ghc for cabal

---

nvm.sh

Following #1319 , rename NVM_CPU_THREADS to NVM_CPU_CORES
cc/ @GeorgeAdams95

Rename NVM_CPU_THREADS to NVM_CPU_CORES

---

nvm.sh

Currently nvm is detecting the number of processors available for building on aix. I have managed to improve this to get the number of threads

update nvm.sh to detect number of cores on aix

---

nvm.sh

This can also help us use the more flexible pattern matching in "case" in future.

[Refactor] Use "case" instead of multi "if"

---

README.markdown

The origin badge will link to the GitHub cached badge image which is meaningless to us, link to the release page will be much more meaningful.
Tested with `make release`

[Docs] Link version badge to the release page

---

README.markdown

Resolves https://github.com/creationix/nvm/issues/1377

Only `nvm install` if we can't `nvm use`

---

install.sh
test/install_script/nvm_install_dir

Use $HOME variable in NVM_DIR

---

nvm.sh

This PR enables nvm to work on nases (similar to https://github.com/robbyrussell/oh-my-zsh/issues/4376) by checking if `tput` exists before calling it.

Enable working without tput.

---

.travis.yml
README.markdown
package.json

Introduce [doctoc](https://github.com/thlorenz/doctoc) to help maintain "Table of Content", make the "Table of Content" maintenance work easier, and won't miss anything important.
Please review the change of README.markdown with whitespace **ignored**, could be easier to find out the real diff, you can also see there is a item missed before.

Introduce doctoc for "Table of Content" generate

---

nvm.sh

This was an "oops" on my part when I was testing changes for my work that was later adapted & merged in https://github.com/creationix/nvm/commit/f1bca106a8f5fc6a4b88b5ef30603cf31ea531f1.
LibreSSL is never installed as a `libressl` as it is intended to be a replacement for `openssl` as much as possible, and consequently the executable is called `openssl`.

nvm: remove libressl command support

---

bash_completion
install.sh
test/install_script/nvm_profile_is_bash_or_zsh

1. Since `NVM_PROFILE` will be a full path, the detection was not working properly without `*/` prefix.
2. The origin bash_completion source prompt in installation was:
```sh
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
&& [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```
Which will cause this error if you don't manually remove the comment:
```
-bash: x: line 2: syntax error near unexpected token `&&'
-bash: x: line 2: ` && [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion'
```
Which is inconvenient, so I removed the ` &&` prefix, and let the `bash_completion` to detect if `nvm` loaded.
3. bash_completion didn't detect if `nvm` already loaded or not, so it'll …

bash_completion fixes

---

nvm.sh

[Fix] Install failed should return correct exit status, fix #1347

---

nvm.sh

By manpath's man page in Ubuntu 16.04:
> If $MANPATH is set, manpath will simply display its contents and issue
> a warning.
By fa22d712ff7367fc0ecc87bbe8801d77303068e3 for #1413, `nvm` now will
declare the "MANPATH" variable, no matter if it's set or not, so in the
situation that $MANPATH is set, you'll get the warning:
> manpath: warning: $MANPATH set, ignoring /etc/manpath.config

[Fix] declare MANPATH if and only if it's not set

---

README.markdown

1. If we are not going to install nodejs or io.js from source, we may
not need to have c++ compiler or libssl-dev package
2. the `build-essential` and `libssl-dev` packages should work on all
the Debian and Ubuntu based GNU/Linux distros
3. Remove useless blank lines

[Docs] Update Installation section

---

nvm.sh

remove extra pair of quotes that vim suggests as syntax error in line 784

fix open string in line 784

---

.travis.yml

Unlike other built in functions like git fetch or apt-get dependencies,
manual installations won't have retry by default, enabling retry could
help reduce the impact of network issues and furthur prevent getting
build error like Job #1956.21:
- https://travis-ci.org/creationix/nvm/jobs/212640007
Ref:
- https://docs.travis-ci.com/user/common-build-problems/

[Tests] Add retry on urchin setup which has no built in retry feature

---

CONTRIBUTING.md

The origin one looks like it's for PR only, let's add something about the issue?

[Docs] Update CONTRIBUTING.md

---

README.markdown
install.sh
nvm.sh
test/fast/Unit tests/nvm_curl_libz_support
test/slow/nvm_get_latest/nvm_get_latest

Enable `--compressed` parameter on curl to automatically enable
compression on request content by sending coressponding header, if the
server side supports compression format like deflate or gzip, curl will
also decompress the content automatically, so there is no additional
works need to done manually on client side, but just enjoy the benifits
of bandwidth and time saving!
Take https://nodejs.org/dist/index.tab as an example which is last
modified on Tue, 14 Mar 2017 22:41:05 GMT, the compressed transmission
only take 4829 bytes howevet the not compressed on taks 48000 bytes,
which is about 10 times larger!
This feature can be traced back to Sep 3 2002, in curl commit:
- https://github.com/curl/curl/commit/64bbe9dfafc6693a96b742f3133c636385835a19
So should be supported on various …

[New] Enable curl auto compression/decompression

---

.travis.yml

This should make the CI faster.

Improve npm in ci

---

nvm.sh
test/fast/Unit tests/nvm_command_info

Try to get shell version, OS and its version, curl/wget version.

[New] Supercharge `nvm debug` output

---

README.markdown

Add Mac OS "troubleshooting" to README.
It has a section on nvm node version not being found in vim.
It should solve #240 for mac users.

Mac os troubleshooting

---

.travis.yml

Since Ubuntu 12.04 is pretty old now, it's also going to EOL next month,
maybe we can just move on Ubuntu 14.04 first.

[Tests] Move to Ubuntu 14.04 on Travis CI

---

.travis.yml

Though we can't drop add-on but Ubuntu 14.04 doesn't need to install gcc & g++ v4.8 from a ppa, remove them can speed up the build.

[Tests] Remove ppa source since we migrated to Ubuntu Trusty

---

test/fast/Aliases/lts/"nvm alias" should ensure LTS alias dir exists

"$(nvm_alias_path)/lts" may be created during the test, should backup/remove the old one before testing.

[Test] "nvm alias" lts test bug fix

---

nvm.sh

my bad 😭 
maybe we should consider to enable WITHOUT_CURL test back, what do you think?

Fix nvm curl libz support

---

.travis.yml

To prevent #1487 bug appears again.

[Tests] Re-enable WITHOUT_CURL tests

---

nvm.sh

Fix #1487
I'm not sure what's going on here, the fix seems to be violated ...

[Fix] To confirm curl exists before detecting curl libz feature

---

.travis.yml
Makefile

Can help detect one more problem in #1492 and make sure Makefile changes won't break release process!

Test "make release"

---

README.markdown

I found the manual install instructions a bit confusing as they sort of jump into a git clone version in the middle of the manual instruction. I don't think you have to do that first line if you have git/go with git but you do have to do the sourcing regardless so I thought this may be a bit easier to understand. thoughts?

manual install update

---

.travis.yml
test/installation_node/install from source with thread parameter

Fix #1489, Travis CI cache needs `curl`

Speedup travis install src test

---

README.markdown

[Docs] Remove archlinux python tips in "Problems"

---

nvm.sh

I noticed #1363 is not fixed completely.
This PR fixes additional causes.

Additional fix for potentially unbound variables in bash strict mode

---

.gitignore
README.md
nvm.sh
test/fast/Running "nvm unload" should unset all function and variables.
test/fast/Unit tests/nvm_default_packages
test/fast/Unit tests/nvm_get_checksum_alg
test/fast/Unit tests/nvm_get_mirror

This PR adds support for a file containing default packages to be installed with every new version install. 
While the `reinstall-packages` option is great, this file based approach is nice because I can check this file into my personal dotfiles repo.
Note: this idea was adapted from https://github.com/rbenv/rbenv-default-gems. I wanted a similar thing from my node version manager setup.

Add support for ~/nvm/default-packages file

---

nvm.sh

Current wording makes the user expect some sort of check against the internet that maybe even ultimately results in an update to the CLI, but this is not the case.

Fix `--version` help text

---

README.md

If installation is prompted to be successful, yet `nvm` command returns `nvm: command not found` then you might need to restart your terminal instance. Try opening a new tab/window in your terminal and retry.

[Docs] Install script - Improve installation guide

---

nvm.sh
test/fast/Unit tests/nvm_curl_use_compression
test/fast/Unit tests/nvm_curl_version

Added `curl_use_compression` routine to determine whether we should add compression flag to curl routine. Fixed #1549

Curl --compressed handling

---

nvm.sh

Fix `clang_version` does not expand as expected. This fix is sub-product of previous curl compression patch (#1550).
One can verify the correctness of the patch from the following snippet
```bash
#!/bin/bash
fxy() {
echo "${1#v}" and "${2#v}"
}
g() {
echo "h"
}
echo $(fxy g h)
echo $(fxy "$(g)" h)
```

fix: use $() to precompute clang version

---

nvm.sh

from curl man page:
```
-f, --fail
(HTTP) Fail silently (no output at all) on server errors. This is mostly done to better enable scripts  etc  to  better  deal
with failed attempts. In normal cases when an HTTP server fails to deliver a document, it returns an HTML document stating so
(which often also describes why and more). This flag will prevent curl from outputting that and return error 22.
```

[Fix] curl should fail if something wrong, fix #1556

---

nvm.sh

because it's 2017 and it might be confusing for people who are new to node.js

bump the sample version numbers

---

.dockerignore
Dockerfile
README.md

This should help `nvm` development and testing

[New] Introduce Docker environment for nvm

---

install.sh

Speed up the installation and bandwidth and save almost 50% disk space in v0.33.1:
2304KB    ./nvm-origin-install
1296KB    ./nvm-new-install

[New] Speedup process to install nvm from git by dropping commit history

---

README.md

Added this for Linux users who may skip over the bit of information because it looks like it pertained only to OS X. Most developers will know about reopening the terminal window, but noobs don't. ;-)
Fixes #1565

Added 'or Linux' to **Note:**

---

install.sh

Use `--auto` can really help speed up the upgrade and also install process if there is no need to re-compress all the objects, just let `git` to decide it.
Not sure if GitHub has optimized their git backend server, I noticed that now a new clone of `nvm` would only a single pack in the .git objects which means it's already compressed, we don't need to force it.

[New] Add `--auto` to git gc to speed up install & upgrade

---

nvm.sh

Not sure if it exists anywhere else but macOS, may help debug in situation like #1553 and #1577 
e.g.
- `iTerm.app`
- `Hyper`
- `Apple_Terminal`

[New] Print $TERM_PROGRAM in nvm debug if it exists

---

install.sh

This can help improve the result of garbage collection. By tracing the [doc](https://git-scm.com/docs/git-reflog/1.5.0) of `reflog`, I think it's a feature just come with `reflog` from the beginning, which is git v1.5 series since 2006.

[New] Clean up git reflog history before git gc

---

nvm.sh

`nvm_unload` was unsetting `RC_VERSION` instead of `NVM_RC_VERSION`. Am I correct in thinking this was a typo?

Also unset NVM_RC_VERSION when unloading

---

.travis.yml

Travis CI now provides the latest ShellCheck and I believe that we don't need to maintain our own installation any more so that we can save both time and resources!

Remove the manual ShellCheck install proecss on Travis CI

---

install.sh

Original codes will print like:
```
=> Downloading nvm as script to '/root/.nvm'
=> Profile not found. Tried  (as defined in $PROFILE), ~/.bashrc, ~/.bash_profile, ~/.zshrc, and ~/.profile.
=> Create one of them and run this script again
=> Create it (touch ) and run this script again
OR
=> Append the following lines to the correct file yourself:
```

[Fix] install.sh shouldn't use not existed variable

---

nvm.sh

I have a [Bash function](https://github.com/citrusui/functions/blob/120b525d11da1a5d8fbdff80f0f68bd06fd5d171/.functions#L6) that I use to clear out my `apt` and `nvm` caches.
---
If you weren't aware `nvm` was on your system, the last line (above) is likely to cause some confusion. **Here's a simple fix:**

Make `nvm cache clear` message less ambiguous

---

README.md

This sentence broke my brain when I read it the first time :) I hope this helps.

Added missing piece

---

nvm.sh
test/installation_node/install LTS

Fix issue 1664 unassigned variable 20171115

---

nvm.sh
test/fast/Unit tests/nvm_ls_current

The `$path` is used by zsh itself.
Rename `path` to `path_`.
Ref:
"The lower-case version of PATH is an array parameter
bound to the scalar upper-case parameter."
-- http://www.zsh.org/mla/users/2015/msg00178.html

Fix for $path used by zsh

---

install.sh
test/install_script/nvm_install_with_node_version

Hi,
I found a bug in `nvm_install_node` function, it overrides the variable NODE_VERSION, which blocks the installation of node in the install.sh script! More details below..
I did some tests locally with the install.sh script, and the I found that the problem in in the function `nvm_install_node` in [install.sh](https://github.com/creationix/nvm/blob/master/install.sh#L143) script.
One solution is to change the name of the local variable to something other than NODE_VERSION
You could test it using these 2 scripts:
I ran tests on ubuntu 16.04 servers
- Current version [0.33.6] test script:
`export NODE_VERSION=8 && sudo curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash`
Expected result: nvm should install node 8
Result: node 8 doesn't get installed …

Fix a bug that block that installation of node in install.sh

---

nvm.sh
test/fast/Unit tests/nvm_die_on_prefix

@zkat @iarna: I would dearly love your input on this change; if this env var checking is good, then I can next replace `npm config get prefix` with "searching .npmrc files", which will give nvm a huge performance boost.

`nvm use`: perfect pre-npm-config env var checking

---

bash_completion
install.sh
nvm.sh

ShellCheck v0.4.7 just released 6 hours ago and hopefully will be deployed on Travis CI soon.
This is the fix for [SC2207](https://github.com/koalaman/shellcheck/wiki/SC2207) and [SC1117](https://github.com/koalaman/shellcheck/wiki/SC1117)

ShellCheck v0.4.7 fixes

---

README.md

Alternative to #1581, though I would say nvm should strip whitespace from the version number in .nvmrc.

Explain .nvmrc better

---

README.md
install.sh

I didn't see relevant tests to if git produces output or not, so haven't added any. I did test reinstalling with this commit, and it does do as it describes, removing the detached head warning.
I didn't add `--quiet` to the git clone, but it's worth considering, or if it should be kept for a download progress indicator.

Don't give detached HEAD advice when installing

---

README.md
test/install_script/nvm_install_with_aliased_dot

I think, the backslashes are not needed.

Add escape sequences and test

---

nvm.sh

`FreeBSD` and `SunOS` would be better than `freebsd` and `sunos` for display/human reading :)

Display FreeBSD and SunOS with correct caps

---

Dockerfile

Use pre-built static release binary instead of building ShellCheck from the source code, this change would save disk space, time, and much computing resources.
Docker image size:
Original: `1.31GB`, New: `569MB`
Compressed Docker image size:
Original: `319MB`, New: `223MB`
(See: https://hub.docker.com/r/peterdavehello/nvm/tags/, `v0.33.8` vs `v0.33.8-new`)
It also saves more than 50% build time, 9:50 vs 4:15 on my computer.

Optimize ShellCheck installation in Docker image

---

README.md

To reflect the latest optimization.

[Doc] Update Docker image build info in README.md

---

install.sh
nvm.sh

Just take a deeper look to find out those commands suppose to have `command` prefix but was missing, so fix now.

[Fix] Add missing "command" prefixes for few commands

---

nvm.sh

This could help debug :muscle:

[New] Add "$PATH" to `nvm debug` output

---

nvm.sh

We don't need to use a longer command to redirect the standard output but we can directly ask grep to be quiet :)

Use grep `-q` parameter instead of redirect to /dev/null

---

nvm.sh
test/slow/nvm reinstall-packages/setup_dir
test/slow/nvm reinstall-packages/teardown_dir
test/slow/nvm reinstall-packages/works with no installs

[Fix] Prevent install/link when no packages found

---

bash_completion

```bash
command -v nvm
```
is a lot faster than
```bash
nvm
```
period.
This significantly cuts shell login time.

Reduce bash_completion startup time

---

install.sh

Add a new line to separate code block and the prompt message, improve the output readability
Old:
```
=> Compressing and cleaning up git repository
=> Profile not found. Tried ~/.bashrc, ~/.bash_profile, ~/.zshrc, and ~/.profile.
=> Create one of them and run this script again
OR
=> Append the following lines to the correct file yourself:
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
=> Close and reopen your terminal to start using nvm or run the following to use it now:
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
```
New:
```
=> Compressing and cleaning up git repository
=> Profile not found. Tried ~/.bashrc, ~/.bash_profile, ~/.zshrc, and ~/.profile.
=> Create one of them and run this …
```

Improve install.sh prompt output, add a new line

---

bash_completion
install.sh
test/install_script/nvm_detect_profile

For more info visit -> https://github.com/creationix/nvm/issues/1707
Credit goes to @pecigonzalo for figuring out the issue, I just did the work to put it in the install script and made sure that it did not conflict with bash.
Just run the install script in zsh to see working. Also please test that the install script still works in bash :)
Fixes #1707.

Add auto completion support to zsh

---

nvm.sh
test/slow/nvm_get_latest/nvm_get_latest

curl output is turned off by `-s` in the same place, we should unify the behavior on wget, also, this help removes those wget outputs that can't fit our coding style tests. cc #1739

Turn off wget's output in nvm_get_latest()

---

README.md

Ref: https://stackoverflow.com/a/7979255
Fix #1772

[Doc] Fix manual install & upgrade guide

---

nvm.sh

`nvm debug` result in #1744 didn't detect the os version properly, this PR could solve it.

Improve OS version detection in `nvm debug`

---

.editorconfig
.travis.yml
package.json

[EditorConfig](http://editorconfig.org/) is a famous open source project which can help us maintain part of the coding style easily, including:
- indentation (tab or space, indent size, tab width)
- trailing space
- end of line char
- final newline char at end of file
and some other features ...
It's supported by **GitHub**(and some other IDEs, editors) **natively**, so commits made on GitHub web GUI will simply follow the config, and most of the famous IDEs/editors like vim, atom, vscode, sublime, emacs, notepad++, gedit, etc, also support it easily by using plugin/extension, it's also introduced in many projects to help maintain the code readability, coding style, I believe it worth us to use it in nvm, we can save some commits for coding style fixing by using EditorConfig, and can …

[New] Add EditorConfig to help maintain part of coding style

---

nvm.sh
test/fast/Running "nvm use" should drop CR char automatically.

Improve how we read the version in `.nvmrc` to avoid the impact of `CR`/`CRLF` as newline char.
Fixes #1015. Fixes #1712.

[Fix] Improve .nvmrc reading process

---

nvm.sh

The same trick as how did we speed up installation script.
Origin time spent for 1000 times `nvm_list_aliases` & `nvm ls`:
```
$ time for a in {1..1000}; do nvm_list_aliases > /dev/null; done                                                                             
real    16m38.301s
user    1m24.416s
sys     1m21.192s
$ time for a in {1..1000}; do nvm ls > /dev/null; done                                                                                                              
real    20m55.143s
user    2m4.852s
sys     1m57.508s
```
New time spent for 1000 times `nvm_list_aliases` & `nvm ls`:
```
$ time for a in {1..1000}; do nvm_list_aliases > /dev/null; done
real    11m59.601s
user    2m0.272s
sys     2m23.560s
$ time for a in {1..1000}; do nvm ls > /dev/null; done
real …
```

[Refactor] Speedup nvm_list_aliases() / `nvm ls`

---

README.md

facilitates older `git` fetching tags so that it can actually upgrade properly
fixes #1772 ... again. 🤷‍♂️

add --tags to git fetch in manual upgrade

---

bash_completion

Correct the indent and make the code more readable

Improve bash_completion coding style

---

README.md

fix failing if check in autoload script

---

README.md

The script isn't working if .nvmrc file had a diferent version of node

fix for .nvmrc script

---

nvm.sh

- https://github.com/koalaman/shellcheck/wiki/SC2235

Fix ShellCheck SC2235 issue

---

install.sh
test/install_script/nvm_detect_profile

this is done by checking if the user supplies `PROFILE=/dev/null` when
running `install.sh`, the `nvm_detect_profile` function will not output
any strings, causing `nvm_do_install` to skip adding `SOURCE_STR`.
tests are included.

allow user to explicitly opt out of nvm adding the source string

---

nvm.sh
test/fast/Aliases/setup
test/fast/Running "nvm deactivate" should unset the nvm environment variables.
test/fast/Running "nvm uninstall" should remove the appropriate directory.
test/fast/Running "nvm uninstall" with incorrect file permissions fails nicely
test/installation_node/install hook

For some context, this was causing issues described in https://github.com/getsentry/sentry/pull/8623.
`nvm_is_version_installed` should not be checking for the presence of an installed node version by simply checking the presence of a directory in `versions/node`. It just isn't a strict enough check. One step would be to check for the presence of an executable `bin/node`, which is what this PR implements.
Even more strict would be to actually try and invoke `bin/node` itself afterwards, and comparing `[ "$(node -v)" = "v${1}" ]`. Please let me know if that sounds good, or if you have any questions.

Improve nvm_is_version_installed to check for a node executable instead of root dir

---

nvm.sh
test/fast/Unit tests/nvm_change_path

This change modifies `nvm_change_path`: it makes sure that nvm's directory is in front of any system directories.
I.e. it'll replace the path in place, like it currently does, unless it's being shadowed by system directories, in which case it'll prepend again.
Includes a unit test to make sure there'll be no regression on this.
Fixes #1652.

Prepend instead of changing if shadowed by system dirs (fixes #1652)

---

Dockerfile

Improve and update Dockerfile

---

README.md
install.sh
test/install_script/nvm_install_dir

Fixes #1088, fixes #1882.
I haven't really tried it, so would be good if someone tried it at least.

Fix: XDG_CONFIG_HOME compatible

---

bash_completion

When using Oh My Zsh the ZSH_DISABLE_COMPFIX flag allows the zsh completion system to use files in directories it deems to be insecure.
In the case of the ZSH_DISABLE_COMPFIX flag not being true I added the -i flag to compinit. This flag will cause the zsh completion system to ignore files in directories it deems to be insecure. If this flag is not used the user will be prompted to either ignore insecure directories or abort compinit. Ignoring the insecure directories manually is the same as using the -i flag and aborting will cause autocompletion in zsh to fail. I believe -i would be the sane default here and this would be shared with Oh My Zsh.
Here is the relevant documentation on compinit: http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Use-of-compinit
And here is an …

Add support for ZSH_DISABLE_COMPFIX flag.

---

install.sh

Print an error and exit the script if $METHOD is set to something unexpected.
In my own personal case, Salt was setting $METHOD to "loopback", and I did not realize it. With this patch, the script output will make it clear what's going on, and it will not pretend to complete successfully.
I did a small amount of testing of my own, but I don't have the tools or experience to complete all the testing asked for in CONTRIBUTING.md. Can someone else help with that?

Logic for when $METHOD is something unexpected

---

README.md

Add section to automatically invoke `nvm use` when `cd`-ing in/out of project directories.
This is intended to replace #1108, #1677, #1678, which seems to be abandoned PRs.
I am not using `builtin` here as it allows users to override `cd` using another function.

Add section on automatic `nvm use` in Bash

---

CONTRIBUTING.md
README.md

There are four kinds of changes in this PR in a single commit:
- Lists should be surrounded by blank lines
- Use only `1.` for ordered list item prefix
- Starting bulleted lists at the beginning of the line
- Fenced code blocks should be surrounded by blank lines
This improvement helps maintain the consistency in the document and the maintainability, readability in the document source.

[Docs] Improve README.md & CONTRIBUTING.md syntax

---

.travis.yml

Ref:
- https://ccache.samba.org/
- https://docs.travis-ci.com/user/caching#ccache-cache

Enable ccache on Travis CI to speed up compilation

---

README.md

Add Ansible task example to show how to install nvm and update it. 
Ansible is a systems administration tool. 
See https://github.com/ansible/ansible
My personal experience of `nvm` is that installing via Ansible is good, and that a good example can help. This example took me about an hour to learn, so I'm hoping to save other people some time. This example is somewhat different than any others that I found on the web. There may be a better way to write it, and if so, please improve it.

Add Ansible task example

---

README.md

Automatically call `nvm use` using `.bashrc` file is broken for directories with to-be-escaped chars.
$ cd the\ folder/
bash : cd : too many arguments
Quoting $@ will fix this issue.

[Docs] fixing cdnvm on .bashrc (auto nvm use)

---

nvm.sh

To help beginners know that 'nvm current' is talking about node and not nvm.

Improve phrasing of 'nvm current'

---

README.md

This is a minor change to make it explicit how the default packages are specified.

README: clarify how to specify default packages

---

nvm.sh

Please note that this is similar but not the same as #1442, since there was a `sort` between `sed` so I need more time to confirm if there will be a problem in the refactor.

[Refactor] Reduce one more `sed` & pipe in `nvm ls` to speedup

---

install.sh

This PR fixes #1962. 
It handles the following cases while installing nvm:
- ~If `NVM_DIR` is defined and set to anything other than the default value, exit installation~
- If `NVM_DIR` is defined and set to a file location not a directory, exit installation
- Otherwise if `NVM_DIR` doesn't already exist, create the folder
- Otherwise, continue

[Fix] Make installation less restrictive when NVM_DIR is set

---

nvm.sh
test/installation_iojs/install from binary

[Fix] Add missing io.js installing message

---

nvm.sh
test/fast/Aliases/"nvm unalias" should not accept aliases with names equal to built-in alias

Also I removed a reference to system as a default alias - since as far as I know it is not a default
I ran into the same issue discussed in this closed issue: https://github.com/creationix/nvm/issues/1051
I wish I could contribute something more substantial to nvm.  Thanks for maintaining this awesome project :)

update error message

---

nvm.sh
test/fast/Unit tests/nvm_stdout_is_terminal

See https://github.com/creationix/nvm/issues/2005#issuecomment-466690060

nvm.sh: added nvm_stdout_is_terminal()

---

README.md

Only works for common aliases like `default`, `system`, `node`, `lts/*`, `iojs` etc.

Update `cdnvm` script to take into account alias

---

install.sh

With the environment variable XDG_CONFIG_HOME set, the installation
script uses the directory $XDG_CONFIG_HOME/nvm now. Before the change
the variable's value with "/nvm" cut off was used, which usually results
in an installation without any subdirectory.

[Fix] Determine correct sub directory if XDG_CONFIG_HOME is set

---

nvm.sh
test/fast/Listing versions/Running "nvm ls" with nounset should not fail.

Adds a default value for NVM_NO_ALIAS so that nvm ls does not error out when run in a bash nounset/-u (no unset vars) environment.
Reproduce error via:
```bash
$ set -u ; nvm ls 12
bash: NVM_NO_ALIAS: unbound variable
```

[Fix] Add default empty value for NVM_NO_ALIAS variable

---

README.md

It was trying to read ./.nvmrc if you cd'ed into a subdirectory of the directory that has .nvmrc, which would give print `-bash: ./.nvmrc: No such file or directory` to stderr and potentially not doing the `nvm install`.

Fix bash auto-use nvm command

---

README.md
install.sh

- Operating system and version: Mac OS X Mojave
- `nvm debug` output:
<details>
```sh
```
</details>
- `nvm ls` output:
<details>
```sh
```
</details>
- How did you install `nvm`? (e.g. install script in readme, Homebrew): Install script
- What steps did you perform? Ran the wget install script
- What happened? $NVM_DIR was set to nvm
- What did you expect to happen? $NVM_DIR should be set to .nvm
I added the following line from the README to my .zshrc:
```
export NVM_DIR="${XDG_CONFIG_HOME/:-$HOME/.}nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
```
I couldn't figure out why nvm wasn't loading, until I realized that 
`echo NVM_DIR="${XDG_CONFIG_HOME/:-$HOME/.}nvm"` outputs `NVM_DIR=nvm`.
Changing the line to `export NVM_DIR="${XDG_CONFIG_HOME/:-$HOME/}.nvm"` fixed …

Set $NVM_DIR to ".nvm" instead of "nvm"

---

README.md

Adds the following information to the "Migrating global packages while installing" section:
- notification that the npm package is explicitly not updated when using the --reinstall-packages-from flag
- information about the --latest-npm flag
- recovery instructions if a user has already updated node with an incompatible npm version

[Docs] Add --latest-npm info to Migrating global packages section

---

README.md

* plus some minor formatting proposals on certain commands

Proposal of formatting on code on string 87

---

README.md

- Clean up readme structure a bit to help with readability. 
- Fix instructions which could lead to a sourcing loop if misinterpreted.
- Guidance should direct macos users to simply copy the source snippet manually into their desired profile file.
Resolve #2123

Improve readme clarity and troubleshooting for install script

---

nvm.sh

This is a very simple change that makes it easy to configure include paths when developing node addons in C/C++. I use vscode which is not aware of the nvm. As a result it cannot find node include files and flags them as errors.
I worked on creating a vscode extension that would handle this but it didn't work well and requires significantly more work than this change. The one line change in this PR is a much cleaner approach (provided that one more NVM environment variable is ok).
I opted for `NVM_INC` as opposed to `NVM_INCLUDE` just because all the other NVM env vars were 3 characters or less.
This allows my `c_cpp_properties.json` file to use the env var like:
```
{
"configurations": [
{
"name": "Linux",
"includePath": [
"${workspaceFolder}/**",
"${workspaceFolder}/node_modules/nan", …
```

nvm.sh - add NVM_INC for the include path

---

README.md

For https://github.com/nvm-sh/nvm/issues/2149

[readme] add nvm intro

---

README.md

Here's my stab at documenting the environment variables. It seemed awkward to just inject `NVM_INC` into the doc without more context so I ended up documenting all the environment variables; it seemed more natural to do so.
I'm not sure what you had in mind for this so let me know what changes you'd like.

document environment variable usage in README

---

README.md

It brakes switching version of node through nvm in directories with space somewhere in it's path:
https://youtu.be/dW1cxfElF5U
I can't imagine why creator of this script is removing spaces from the path, maybe there is a reason for that but I don't know it, please review it then.

Stop removing spaces from nvm_path

---

README.md

This is in response to a popular stack overflow answer that has helped people resolve the "command not found" hiccup: https://stackoverflow.com/a/17707224/2031033
Also mentioned here: https://github.com/nvm-sh/nvm/issues/748

Update install instructions troubleshooting

---

README.md

The default shell for macOS 10.15 is now zsh, by default a .zshrc file is not created, so switch instruction for `touch ~/.zshrc`
Reference: [Catalina replaces bash with zsh as default shell](https://www.theverge.com/2019/6/4/18651872/apple-macos-catalina-zsh-bash-shell-replacement-features)

Update macOS troubleshooting w/ 10.15 zsh default

---

README.md

Fix fish `load_nvm function` in readme.
The `load_nvm` function for fish contained an error on line 8 where it would try to install "N/A" as a node version, instead of the version listed in the `.nvmrc` file.

Fix bug in fish example script

---

nvm.sh

macOS only supports extracting xz tarballs with `tar` in 10.9 and up.
GNU `tar` needs an `xz` executable on the `PATH` to extract xz tarballs.
Fixes #2155.

nvm.sh: Add more xz platform support checks

---

nvm.sh

resolves https://github.com/nvm-sh/nvm/issues/2200
nvm --version for me returns:
0.35.3
nvm -v returns the output of an unrecognized command.
This is issue proposes adding -v as an alias for --version as it is for node, npm, and many other commands. 
I did not add this to any tests.

Add -v Flag #2200

---

nvm.sh

Fixes issue #2120 
Request was to add extra instructions to the help section:
-  nvm_echo '  nvm install node                      Install the latest available version'
-  nvm_echo '  nvm use node                          Use the latest version'
-  nvm_echo '  nvm install --lts                     Install the latest LTS version'
-  nvm_echo '  nvm use --lts                         Use the latest LTS version'
Tests: I did not add any tests

Add suggested lines to help section

---

README.md

Added an example for LTS updates that also reinstall the existing packages.
This is useful for individuals who run the latest LTS version along with global packages and need to update when the LTS version gets bumped

[readme] Add documentation for LTS updates which reinstall existing packages

---

nvm.sh
test/installation_node/install with --alias
test/installation_node/install with --default

Resolves #1867 
This is a follow up the work in PR #1929
I could not push to @kaltepeter 's remote so I have made a new PR. 
> It'd be nice if I could combine
> ✗ nvm install 8 && nvm alias default 8
> into:
> ✗ nvm install --default 8
> Seems like a reasonable request - we could also add --alias=foo (and have --default be a shortcut for --alias=default) to cover the generic case.
ran with:
` --alias=* version`
` --alias=* no-version`
`--default --alias=* version`
Does not return err
` --alias=*  version --default`

Add --alias and --default to Install

---

nvm.sh
test/installation_node/install with --alias
test/installation_node/install with --default

For: `nvm install 8.12.0` after install:
--alias=8 is equivalent to `nvm alias 8 8.12.0`
--default is equivalent to `nvm alias default 8.12.0`
implements #1867

[New] adding default and alias option to `nvm install`

---

README.md
nvm.sh

Addresses https://github.com/nvm-sh/nvm/issues/2261
My first thought was to somehow compare the capitalisation between the user directory name displayed from `$HOME` and the one you'd get from an `ls /Users/`, but that exceeds my bash scripting skills 😅
So all I did was add an extra subsection in the `macOS Troubleshooting` section of the docs, and also add an extra warning when that error appears, if we are on a Mac machine. 
I also made a small update to the `.gitignore` file.

Update docs and add warning for 'nvm is not compatible with the npm config "prefix" option' edgecase error on Mac OS

---

nvm.sh
test/fast/Unit tests/nvm_check_for_help

This fixes #911 
Issue: Prevent flags from being parsed if the help flag is present in the list of arguments to nvm
> Even if nvm doesn't support the --help flag on individual tasks it would be more user friendly to prevent any action being carried out if the --help flag is present
What we did: Check arguments list for help flag and display help then exit without parsing other flags
Test added: nvm_check_for_help

[Fix] ensure `--help` is intercepted on any command 

---

nvm.sh
test/slow/nvm use/Running "nvm use node --silent" doesn't print anything

I ran a test that just ran ```nvm use node --silent``` that I wrote by myself. Unfortunately, I noticed a bug where it still prints out some messages in different cases. This pull request is to fix that bug.
* Added in an argument called ***quiet***  to the nvm_rc_version() function at *line 339*
* Printed anything inside the nvm_rc_version() only in the scenario where quiet mode is off
* Ran the nvm_rc_version() function in quiet mode only if silent mode is on in the "use" command of nvm at *line 2990*
* Ran *nvm_echo* and *nvm_err* inside the "use" command of nvm only in the scenario where silent mode is off (There were 4 scenarios where this was forgotten)
* Created aliases for the --silent flag in ```nvm deactivate``` and ```nvm use```
* Changed the unrequited local declaration of the …

Fixed a bug where --silent mode was failing for nvm use

---

nvm.sh

This is a small optimization of the nvm_auto function: $NVM_CURRENT is only used in the `elif [ "_$NVM_MODE" = '_use' ]; then` part of the conditional, so it should only be set if it's needed.
I source nvm.sh with `--no-use` so this change takes the load time of the whole script from about 40ms down to about 5ms

Small nvm_auto optimization

---

Dockerfile

The workaround came from this GitHub issue comment:
https://github.com/koalaman/shellcheck/issues/1053#issuecomment-357816927
Looks like the problem doesn't exist any more:
```
.
.
.
Step 14/33 : RUN shellcheck -V
---> Running in 4b7a718c1cbf
ShellCheck - shell script analysis tool
version: 0.7.0
license: GNU General Public License, version 3
website: https://www.shellcheck.net
.
.
.
```
The workaround should be removed so that the Dockerfile will be easier
to be understand and read.

Remove ShellCheck Segmentation fault workaround in Dockerfile

---

Dockerfile

locale-gen command seems missing since uncertain point for a while:
```
Step 15/33 : RUN locale-gen en_US.UTF-8
---> Running in fae073c89c01
/bin/bash: locale-gen: command not found
The command '/bin/bash -o pipefail -c locale-gen en_US.UTF-8' returned
a non-zero code: 127
```
This patch should fix the Docker image build

Add missing apt pacakge `locales` in Dockerfile

---

README.md

Automatically call `nvm use`: Ammended the bash script example to call `nvm use` when booting a terminal (previously only called on `cd`).
It means the node version is correctly set for example in VS Code's integrated terminal.

[readme] bash shell integration: Amended example to call cd when booting a terminal (previously only called on cd)

---

.travis.yml

That config was deprecated for a while, reference:
- https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures

Drop deprecated `sudo:` option in TravisCI config

---

nvm.sh
test/fast/Listing versions/Running "nvm ls" should not show a trailing slash
test/fast/Unit tests/nvm_die_on_prefix

Fixes #2315 
This changes out a string comparison to a directory comparison, removes empty lines from versions, and removes trailing slashes from versions.

[Fix] `nvm_die_on_prefix`: use directory comparison rather than string

---

test/fast/Unit tests/nvm_ls_current

Fixes one of the failing tests in #2181
`nvm_ls_current` returns 'system' when `nvm_tree_contains_path` is aliased to return zero, as if nvm is deactivated. This fix instead sets `NVM_DIR` to match `TEST_DIR` so that `nvm_tree_contains_path` passes and the mock executable is actually used. Let me know if this approach is reasonable!
Relevant branches in `nvm_ls_current`:
https://github.com/nvm-sh/nvm/blob/e01060fa2c331d77e306a90288b759010e14758e/nvm.sh#L915-L925

Fix `nvm_ls_current` fast unit test

---

nvm.sh
test/fast/Unit tests/nvm_ls_remote

nvm ls-remote will not filter versions ending with "."
Resolves issue #983.
```
$ nvm ls-remote 5
->       v5.0.0
v5.1.0
v5.1.1
v5.2.0
v5.3.0
v5.4.0
v5.4.1
v5.5.0
v5.6.0
v5.7.0
v5.7.1
v5.8.0
v5.9.0
v5.9.1
v5.10.0
v5.10.1
v5.11.0
v5.11.1
v5.12.0
```
```
$ nvm ls-remote 5.
N/A
```
```
$ nvm ls-remote 5.
->       v5.0.0
v5.1.0
v5.1.1
v5.2.0
v5.3.0
v5.4.0
v5.4.1
v5.5.0
v5.6.0
v5.7.0
v5.7.1
v5.8.0
v5.9.0
v5.9.1
v5.10.0
v5.10.1
v5.11.0
v5.11.1
v5.12.0
```

ls-remote accepts versions ending with a dot

---

nvm.sh
test/fast/Unit tests/nvm_die_on_prefix

Fixes #2251. Fixes #1774. Fixes #1694. Fixes #1277. Fixes #1261. Fixes #1242. Fixes #966. Fixes #926. Fixes #860. Fixes #781. Fixes #709. Closes #1826. Closes #730.
This PR removes the call to `npm config get prefix` on `nvm use`, instead partially replicating the algorithm npm itself uses to build up its config. Since we don't have to actually produce a config, merely detect if any option is set that would influence `npm config get prefix` (namely, `prefix` or `globalconfig`), the checks are simpler and can be done relatively quickly. Previously, #1679, 1458de72934a33b279ac3cbb9d648295501ae74d, 8ee6f3035292b46fe4067a089d2b0752f4ce0e98, and a1def710628a2fc71552a9f79f9b53f3d6a3b8db implemented partial forms of this checking. This PR specifically adds the checks for npmrc files, which …

[Perf] `use`/`nvm_die_on_prefix`: replicate npm config algorithm and remove `npm config` call

---

package.json
test/fast/Running "nvm use iojs" uses latest io.js version

Fixes #2181
This makes `npm run test/fast` start the test suite from within a fresh login shell, effectively removing the `NPM_CONFIG_...` variables that caused most tests to fail in #2181. I've run this in both zsh and bash, and all fast tests pass.
`$TERM` is included in the fresh environment to prevent tests that rely on the color output of `nvm_print_formatted_alias` from failing. 
`node_modules/.bin` is still added to the path by the makefile, so I temporarily remove it in `test/fast/Running "nvm use iojs" uses latest io.js version` for the same reason as #2322.
This change could probably work for the other suites too! I just haven't dug into that yet... let me know what you think! :)

[Tests] Run fast test suite in clean environment

---

nvm.sh
test/fast/Unit tests/nvm_die_on_prefix

This restricts the lines found when searching for `NPM_CONFIG_PREFIX` env vars.
I had trouble getting nvm to work in AWS CodeBuild, because the env vars contained entries such as:
```
BASH_FUNC_nvm()=() {
}
```
Any line containing `NPM_CONFIG_PREFIX` would get selected and evaluated, resulting in very strange error messages:
```
Running command [ -s $NVM_DIR/nvm.sh ] && . $NVM_DIR/nvm.sh
/usr/local/nvm/nvm.sh: line 2230: $(nvm_sanitize_path "${NPM_CONFIG_PREFIX}");: command not found
```
I have to idea why these env vars exist, but this change ensures that they are ignored.
I've added a test case as well, but I haven't run the full test suite. Someone more familiar with nvm may have to double-check this.

[Fix] `nvm_die_on_prefix`: only grep lines starting with env var name

---

.github/workflows/shellcheck.yml
.travis.yml

This adds a github workflow that runs shellcheck on `nvm.sh` and `install.sh`. `nvm.sh` is tested with each shell in `[bash, sh, dash, ksh]` and `install.sh` is tested with just `bash`. I think submitting this PR should run the workflow, but just in case, [here](https://github.com/reasonablytall/nvm/actions/runs/370757305) is an example of this change running on my fork.
Unfortunately shellcheck [does not support zsh](https://github.com/koalaman/shellcheck/issues/809), which is why it's omitted from the matrix.
I ignored [SC1001](https://github.com/koalaman/shellcheck/wiki/SC1001) in nvm.sh because there are three instances where `\command ...` is used (i'm guessing) to suppress aliases. More recent versions of shellcheck automatically ignore these instances, but not the older version …

[actions] Add shellcheck workflow

---

README.md
nvm.sh
test/fast/Aliases/nvm_list_aliases calls nvm_get_colors
test/fast/Aliases/nvm_print_alias_path calls nvm_get_colors
test/fast/Aliases/nvm_print_formatted_alias calls nvm_get_colors
test/fast/Set Colors/nvm_echo_with_colors
test/fast/Set Colors/nvm_err_with_colors
test/fast/Set Colors/nvm_print_default_alias calls nvm_get_colors
test/fast/Set Colors/nvm_print_versions calls nvm_get_colors
test/fast/Unit tests/nvm ls-remote
test/fast/Unit tests/nvm set_colors
test/fast/Unit tests/nvm_get_colors
test/fast/Unit tests/nvm_print_color_code

Fixes #1000 : Configurable output colors
We've added a --set-colors command and a related message in the help menu to let the user pass in five color codes and we replaced the colors in the ls, alias and ls-remote functions with the color codes set to the original defaults so that they can be changed by the user's choice.
We looked for other functions that might output in color but didn't see others. Please advise if there are others that need colors.
We tested by running the commands in the terminal, but did not add tests for these changes.

Set colors

---

.github/workflows/release.yml
.travis.yml

Adds a workflow that tests the `make release ...` process by running it with a placeholder version (`99.99.99`) and ensuring that a new tag is created. 
This replaces the previous travis process and adds the tag check as a bonus.

[actions] Add release test workflow

---

install.sh
test/install_script/nvm_check_global_modules

It's an especially clever check — just a substring match — but should cover a typical situation.
Fixes #2339.

[Fix] `install`: Ignore npm command under $NVM_DIR when checking for global modules

---

nvm.sh

When the `nvm` function is called by a script which itself uses a variable
named `i`, `nvm` clobbers the caller's variable. This happens even if the
caller has declared its variable as local.
See note 1 on https://tldp.org/LDP/abs/html/localvar.html#FTN.AEN18568

Use local variable when looping over args

---

README.md

please refer to the issue https://github.com/nvm-sh/nvm/issues/2204

[Docs] git install document update, sourcing nvm

---

README.md

Updated warning for insecure directories while homebrew is installed. Raising PR for https://github.com/nvm-sh/nvm/issues/2361

[Docs]: Updated README.md to include homebrew unsecure dirs warning

---

install.sh
test/install_script/nvm_install_with_node_version

Simply copy/pasting nvm_grep function from nvm.sh to install.sh makes the test `nvm_install_with_node_version` to fail.

[Issue] Adding nvm_grep in install.sh makes CI to fail

---

install.sh
test/fast/Unit tests/nvm_download
test/install_script/nvm_download

Playing a bit more with git, I changed a bit the code compared to the other same PR, which is more compact but changing a bit the previous code though.
It still have the exact same test that pass and which I think cover rather well all the cases I could think of.

[Tests] Add unit test for nvm_download

---

nvm.sh

As per #2420, when using `nvm install` with an already installed
version, Bash (and potentially other shells) may emit an unbound
variable error when `set -u` is set. The presence of the error depends
on specific shell versions, but appears to happen in MacOS 11.1 (Big
Sur) using a recent Bash version installed via Homebrew (as of this
writing).
The fix accesses `ALIAS` correctly for the case where it is not set by
an `alias` option to `nvm install`.

Fix potential unbound var error on nvm install

---

README.md

Reference: https://github.com/nvm-sh/nvm/issues/2350#issuecomment-764845508
Closes #2350. Closes #2422.

[readme] Add macOS troubleshooting instructions for M1 chip

---

README.md

Updates the troubleshooting instructions.
- Switching the architecture does not require opening a new terminal session. Doing so will run that session using the default and result in Node being built from source for arm64 instead of downloading the x86 binary.
- After installing Node, the architecture can safely be reverted using `arch`.

[readme] Update M1 macOS troubleshooting instructions

---

README.md

当函数名为find-up时，定时运行会报以下错误：
```
`find-up': not a valid identifier
```
修改为find_up即可修复该问题

[readme] update `cdnvm` implementation

---

nvm.sh
test/fast/Unit tests/nvm_install_binary_nosource
test/installation_node/install from binary with binary flag set

This PR aims to add the `--b` flag that skips source download and  install from binary only.'
Closes : https://github.com/nvm-sh/nvm/issues/2114

[New] `install`: add `-b` flag to skip building from source

---

nvm.sh
test/slow/nvm exec/Running 'nvm exec' with help should not parse

Running `nvm exec stable -- node --help` shows nvm's help, not node's. This change stops help parsing when encountering a `--`.

[Fix] `exec`: `--` should stop argument parsing

---

nvm.sh

num_of_cpu check is missing for OBSD Kindly merge the changes.

added parallel build support for obsd

---

nvm.sh
test/fast/Unit tests/nvm_alias LTS-N

Title says it all.
fixes #2461

[Fix] `nvm_alias`: ensure `lts/-1` returns the one before `lts/*`

---

.github/workflows/lint.yml
README.md
package.json

Adds missing headings in the readme.
Closes #2413

[readme] add headings to certain sections

---

README.md

The instructions seemed to encourage the misconception that `arch -x86_64 zsh` somehow modifies the default architecture for `zsh`, an operation which would need to be "reverted".
In fact, `arch -x86_64 …` merely spawns a new process under the selected architecture.

Clarify the M1 shell instructions

---

nvm.sh
test/fast/Unit tests/nvm_get_arch

Several people in the Raspberry Pi community have had issues with `nvm`. We realized that everyone affected had one thing in common: they were using armhf (armv7l) Raspberry Pi OS, but had enabled the arm64 kernel.
`nvm` mistakenly detected the OS to be 64-bit arm, while in reality it was armhf. This pull request solves the problem.

nvm_get_arch(): fix for arm64 kernel running armv7l userland

---

README.md

I was trying to follow the instructions on the README on a fresh macOS installation and tripped over the fact that Rosetta 2 wasn’t installed. I got the following error:
```console
$ arch -x86_64 zsh
arch: posix_spawnp: zsh: Bad CPU type in executable
```
This pull request mentions that you must have Rosetta 2 installed and provides instructions on how to do it. I ended up installing Rosetta 2 by opening OBS, which is Intel-only when installed via Homebrew as of 2021-04-05, and I borrowed the command to install Rosetta 2 on the command line from this thread: https://apple.stackexchange.com/questions/408375/zsh-bad-cpu-type-in-executable

Improve README about Macs with M1 chips

---

bash_completion

Fixing #2489. Not sure about testing, didn't do anything. Please advise me on how to do it.

[Fix] check if `compinit` is called before calling it

---

install.sh
test/install_script/nvm_detect_profile

This attempts to detect the users default shell rather than the shell the install script is running in, which will always be `bash` if following install instructions. Fixes #2555

Detect correct profile in install.sh based on $SHELL var

---

Dockerfile
README.md

Ubuntu 16.04 is EOLed.
The `realpath` package is no longer existed in the new versions of Ubuntu and should be removed.

[Dockerfile] Update dated base image from Ubuntu 16.04 to 18.04

---

.github/workflows/latest-npm.yml
.github/workflows/lint.yml
.github/workflows/rebase.yml
.github/workflows/release.yml
.github/workflows/require-allow-edits.yml
.github/workflows/shellcheck.yml
.github/workflows/toc.yml
.github/workflows/windows-npm.yml

This PR adds specific permissions to the existing workflows under .github/workflows.
I have implemented a [GitHub App](https://github.com/apps/step-security) to automatically restrict permissions for the GITHUB_TOKEN in workflows. This is a security best practice as per the GitHub Actions [hardening guide](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions). 
I am trying the App out on public repositories, by forking them, installing the App on the fork, and manually creating PRs with the fixed workflows. The App automatically fixes permissions when a PR is created that creates a new workflow, so feel free to [install it](https://github.com/apps/step-security) for future workflows, or try it out on other repos. 
I have manually reviewed the …

Add specific permissions to workflows under .github/workflows

---

bash_completion

If `cd` is patched (overridden) and prints something to stdout/stderr, completing `nvm use` with tab-tab erroneously displays this output alongside the completion options.
```bash
function cd(){ echo EXTRA INFORMATION IN MY FACE; command cd "$@"; }
nvm use <TAB> <TAB>
```
Completion words should be e.g 
`default      EXTRA        FACE         IN           INFORMATION  iojs         MY           node         stable       unstable     v14.17.6`
This is fixed if function `__nvm_aliases` in `bash_completion` uses `command cd` instead of bare `cd`.

[Fix] `bash_completion`: be robust when `cd` is overridden

---

README.md

Bash terminal was throwing error: `bash: cd: too many arguments` when directory had some spaces in the name.
The quotes around `$PWD` fixes this issue

updated automatic call script for bash

---

README.md

Fix a typo where the word 'run' was written twice.

[readme] remove duplicate word 'run'

---

nvm.sh

[Fix] Regression in 2dad045

---

README.md

Do not use the aliased `cd` inside `cdnvm()`.
This avoids an infinite loop when re-reading `~/.bashrc` - eg. if the user does a `source ~/.profile`.

Avoid infinite loop in cdnvm()

---

README.md

I also gave more up to date versions for example of  `nvm install` and `nvm which` as well as your pointer section
I love your project by the way.
I hope you like my minor suggestions.  I thought it could be confusing to new people of node if we refer to such old versions that no one uses anymore.

fixed small  typo afew to a few

---

README.md

Just added the info to restart the bash terminal if `command -v nvm` does not ouput anything or gives an error after installation. It was mentioned somewhere earlier but when I read it, I just took note of the verification section, not the part before where the info was mentioned.

Add info to restart bash if verification not working in verification section

---

README.md

Allow newbies to get a quick understanding of how NVM works right from the start.

[readme] Add quick intro to `nvm`

---

nvm.sh
test/fast/Unit tests/nvm_strip_path

`nvm_strip_path()` will fail if `NVM_DIR` contains meta characters such as `#*.^$[]\`.
```bash
$ NVM_DIR='/#'
$ echo "${NVM_DIR}/1/bin:${NVM_DIR}/2/bin:${NVM_DIR}/3/bin:/usr/bin" | sed \
-e "s#${NVM_DIR}/[^/]*/bin[^:]*:##g" \
-e "s#:${NVM_DIR}/[^/]*/bin[^:]*##g" \
-e "s#${NVM_DIR}/[^/]*/bin[^:]*##g"
sed: 1: "s#/#/[^/]*/bin[^:]*:##g
": bad flag in substitute command: '#'
```
`awk` is capable to solve this problem.
```bash
$ NVM_DIR='/#*.^$[]'
$ printf %s "${NVM_DIR}/1/bin:${NVM_DIR}/2/bin:${NVM_DIR}/3/bin:/usr/bin" |
awk -v NVM_DIR="${NVM_DIR}" -v RS=: '
index($0, NVM_DIR) == 1 {
path = substr($0, length(NVM_DIR) + 1)
if (path ~ "^/[^/]*'"${2-}"'.*$") { next }
}
{ print }' | paste -s -d: -
/usr/bin
```

Use awk for reliable path stripping

---

README.md
package.json

This test use the npm package: markdown-link-check to help check if all the links in the documentation is alive.
Since markdown-link-check hasn't support relative links, to make the test passed, move this link to use absolute URL so that we can introduce the new test. cc tcort/markdown-link-check#10

[Tests] Add markdown-link-check on Travis CI

---

.travis.yml

🤷‍♂️ who knows if this works lets find out

[Tests] blacklist expired LetsEncrypt CA

---

README.md

Describe another failure case for installing node versions from source on mac arm64 machines.
It seems to be related to https://github.com/nodejs/node/issues/39313 (which describes a similar issue).

Describe another failure case for installing node versions from source on mac arm64 machines

---

README.md

Nesting the `elif` at the same level as the `if` and `fi` makes it clear which code applies to which branch (no .nvmrc file / found .nvmrc file).
I wasted a while looking at it trying to work out how it did anything if there was a .nvmrc file, because obviously the `if` didn't match and I couldn't see the `elif` branch.

Balance the if statement in bash example

---

README.md
nvm.sh
test/fast/Unit tests/nvm_get_download_slug

Changed configuration in **nvm_get_download_slug()** function, made condition for **darwin** based OS running on **arm64** arch i.e, **MAC M1**. 
If so, then change HOST_ARCH to **x64** so that NVM will fetch **x64 arch** package from node repository which is the only package node currently having for darwin systems but no arm64 based packages
- Macbook M1 ARM64 architecture problem that does not allow us to use default terminal for installing node packages using nvm, please [refer here](https://github.com/nvm-sh/nvm/issues/2350)
- What we did was use a rosetta-2 terminal for installing different node versions using NVM. It was creating problems for automation developers who use scripts to run operations, and it was not always possible to run the script on a single installed version of …

[Fix] `nvm_get_download_slug`: better architecture selection for M1 Macs

---

.github/workflows/latest-npm.yml
.github/workflows/lint.yml
.github/workflows/rebase.yml
.github/workflows/release.yml
.github/workflows/require-allow-edits.yml
.github/workflows/shellcheck.yml
.github/workflows/toc.yml

This PR adds the `step-security/harden-runner` GitHub Action to the lint.yml workflow to restrict outbound calls. This is a new GitHub Action that provides runtime security for GitHub hosted runner. As of now, it can be used to set allowed outbound traffic for workflow runs to prevent credential exfiltration. You can see the results of running this on a fork [here](https://github.com/varunsh-coder/nvm/runs/4288537584?check_suite_focus=true#step:3:4). 
@ljharb would love to pilot `step-security/harden-runner` on this workflow to get feedback and improve the experience. Do let me know if you have any questions. Thanks!

[actions] add step security runner

---

nvm.sh
test/fast/Unit tests/nvm_extract_tarball

This PR special-cases the archive extraction code when executed on OpenBSD. This is to workaround the use of the `-J` and `--strip-components` options, which OpenBSD's `tar` does not support. If the `xz` format archive was downloaded, it correctly calls `xzcat` and pipes the output to `tar`. If not, it correctly calls the `tar` with the normal compression flag. In either case, it does not append the `--strip-components=1` option, but rather uses the `-s` option to perform `ed(1)`-style basic regex replacement on the path.
This is tested to execute correctly on OpenBSD 7.0 (current release as of this PR). It does not address compilation issues of the downloaded `node` source code, as mentioned in #2134, which will likely require upstreaming of some subset of the OpenBSD-specific source …

Update tar syntax to support OpenBSD.

---

nvm.sh

TL;DR: `nvm install` fails in Arch's `makepkg` environment when `/sbin/init` does not exist. No idea (yet) why exactly this happens, but slightly modifying the line checking for `/sbin/init` here seems to fix things.
A few more details/reasoning:
In some very rare circumstances, a non-existing `/sbin/init` seems to cause an `nvm install` to fail without any 'good' hint as to why it fails. (It seems like the commit 7f2ccd51d4c20cd23d7ba79e4c19f06c40b68470 made it especially hard to pinpoint what's going on here, because even if things silently fail there, it might still cause a script failure in those circumstances.
This could look like this, for example:
```
Downloading and installing node v14.18.1...
Binary download failed, trying source.
```
…and then nothing more.
I am not entirely …

handle nonexisting /sbin/init a bit more cleanly

---

nvm.sh
test/installation_node/install on bash with ERR trap and set -E

(Discussed at length in #2678)
- Move `ls -dl /sbin/init` to the following `if` statement for implicit
error handling (even if enabled, `errexit` and `errtrace` have no
effect in this context)
- Disable errtrace (`set -E`) in nvm_get_arch and consolidate existing
checks for `set -e` and `set -a` into one loop
`nvm install` fails with "Binary download failed, trying source" in Arch
Linux package build scripts. This is the combined result of `makepkg`
running these scripts with ERR trap inheritance enabled, and the lack
of error handling when `nvm_get_arch` calls `ls -dl /sbin/init`. If
`/sbin/init` doesn't exist, the ERR trap set by `makepkg` exits
non-zero and the operation fails.

Fix `nvm install` error if /sbin/init is absent and errtrace is enabled

---

README.md

A minor correction for `nvm.sh` in the "Macs with M1 Chip" section in README.md

Correct nvm.sh path in "Macs with M1 Chip" section in README.md

---

README.md

Variables in test arguments must be interpolated, or the test always fails and leading to reloading of nvm, which is way slower.

[Docs] fix fish load_nvm variable interpolations

---

README.md

Send output from `load_nvm` to `/dev/stderr`

---

nvm.sh
test/fast/Unit tests/nvm_ensure_version_installed
test/slow/nvm run/Running 'nvm run 0.x' should error out sensibly when 0.x is not installed
test/slow/nvm run/Running 'nvm run' should pick up .nvmrc version
test/slow/nvm use/Running 'nvm use' with nvmrc containing not intalled version

We skip showing version only if we have `.nvmrc` with value and runs `nvm use` or `nvm run`.  If `nvm use v17` or `nvm run v17 app.js` is used we still show the version as seen in the screenshot:
nvm use:
nvm run:
Fixes #2701, #2775

[Fix] `nvm install`: show proper version in `.nvmrc` install instructions

---

.github/workflows/shellcheck.yml
.travis.yml
install.sh

Problems:
* Latest node, v18.10.0, fails at `npm install` on xenial, breaking builder.
* Resolved by running `nvm install --lts` before `nvm install 16`, this sets the default node version correctly for the tests and uses 16 for `npm install`.  This is a workaround which won't be required after migrating from Travis CI to GitHub Actions, where more control over the tests to distro orchestration is possible.
* Some old versions of node won't install on versions of ubuntu newer than xenial, breaking tests. Example: `0.6.21`
* Got the tests passing on xenial so no upgrade is needed at this time.
* Brew removed from Ubuntu runner images. https://github.com/actions/runner-images/issues/6283
* brew was used to install shellcheck, readding brew using `Homebrew/actions/setup-homebrew` …

Resolve CI issues

---

README.md

The instruction list in the `Git Install` section of the `README` was being rendered incorrectly.
Fixes #2822

[readme] Fix Git Install instruction list structure

---

README.md

If cd command fails, return whatever cd returned, instead of marching ahead

[readme] cdnvm(): handle failed dir change

---

README.md

This fixes these two linting errors:
- fqcn-builtins: Use FQCN for builtin actions.
- name: All names should start with an uppercase letter. (name[casing])
Fixes #2860.

[readme] Fix Ansible Linting Errors

---

README.md

The zsh hook in the readme causes `cd` to take unnecessarily long when working in directory tress without `.nvmrc` files due to always calling `nvm version` and `nvm version default`. 
```sh
$ time (nvm version)
( nvm version; )  0.01s user 0.02s system 46% cpu 0.052 total
$ time (nvm version default)
( nvm version default; )  0.07s user 0.12s system 87% cpu 0.213 total
```
We should only call `nvm version` and `nvm version default` if we _left_ a directory with a `.nvmrc` file.
`nvm_find_nvmrc` and `nvm_find_up` are fast, so by creating a similar search, but with `OLDPWD`, unneeded calls to `nvm version` and `nvm version default` are eliminated.

[readme] optimize calling of `nvm version` in zsh

---

README.md

- Update install directions to include `python3`, instead of `python2`, which is deprecated since Alpine 3.13.
- Add both install scripts, depending on different Alpine versions being ran, at request
- Added a side note for users wanting to run Alpine 3.5 - 3.12 regarding older versions of NodeJS
- Update the note regarding Alpine versions supporting which NodeJS versions
Fixes #2895.

[readme] Update Alpine Linux Section

---

README.md
nvm.sh

[Fix] Don't override Mac M1 architecture for node ^14.17

---

install.sh
test/install_script/nvm_detect_profile
test/install_script/nvm_profile_is_bash_or_zsh

Hi there.
I tried to install nvm on my new Macbook air m2 and failed due to the `"Profile not found. Tried ~/.bashrc, ~/.bash_profile, ~/.zshrc, and ~/.profile."` error
I checked my home directory and there was only a `~/.zprofile` file
This PR adds support for `~/.zprofile`

[Fix] `install.sh`: support `~/.zprofile`

---

nvm.sh

As of now there are about 700 node versions according to `nvm_remote_versions`, for which `nvm ls-remote` might take up to 20 seconds to print the versions in a slightly formatted form.
We can get a significant performance improvement by replacing the major part of `nvm_print_versions` with a awk based implementation:
<table>
<tr><th></th><th>Before</th><th>After</th></tr>
<tr><td>Main loop</td><td><code>
real    17.163s
user    6.635s
sys     6.675s
</code></td></td> </td><td><code>
real    0.183s
user    0.108s
sys     0.098s
</code></td></td></tr>
<tr><td>Overall</td><td><code>
real    18.555s
user    6.984s
sys     6.958s
</code></td></td> </td><td><code>
real    1.671s
user    0.508s
sys     0.414s
</code></td></td></tr>
</table>

[perf] `nvm_print_versions`: re-implement using awk

---

nvm.sh

Adding function `alen(arr)` since `length(arr)` is GNU extension. Fixes #2916

improve backward compatibility for non-gnu awk

---

nvm.sh

No need to escape the `/` char in a grep pattern.
This is to fix the below error when using newer grep with `nvm_command_info`
> $ nvm_command_info curl
> grep: warning: stray \ before /
> /usr/bin/curl
This happens with at least GNU grep 3.8 version.

[Fix] grep: warning: stray \ before /

---

nvm.sh

On Debian, the default awk/mawk doesn't support the `--version` option, instead there's mawk specific `-W version`. See https://linux.die.net/man/1/mawk

[Fix] nvm debug: awk: not an option: --version

---

nvm.sh

Remove the call to `ls` that was used to determine the symlink
destination
Reasoning :
* `od` resolves symlink itself due to the use of `fopen`
* Prevent the behaviour of `od` which will hang if the filename is
empty (i.e. `/sbin/init` missing) as it will be waiting for `stdin`
compared to quitting with error if the file just doesn't exist
Closes #3006

Remove unneeded call to ls in `nvm_arch`

---

.travis.yml

Since python 2.x is EOL, default python on the Travis images is 3.x. This PR should fix the issue with builds failing due to that reason i.e. syntax mismatch.

TCI Support

---

nvm.sh

Fixes #3054
Depending on the run, these changes improve the speed of `npm ls` by anywhere from 5% to 30% depending on the run, though it seems to average around 10%. It's not as much as I would like, but it's something.
I can get much better performance if I modify `nvm_list_aliases` to only have one `wait` call and no `sort`. It may be worth adding an option `--unsorted` which does exactly this, but I'm not familiar enough with argument parsing in sh to implement this myself.

[Perf] Improve performance of listing aliases

---

nvm.sh

nvm tries to download & install 64Bit node Versions inside a 32Bit docker container on a 64Bit host

[Fix] recognize 32Bit docker container and use x86 arch

---

README.md

travis-ci.org is deprecated and replaced by app.travis-ci.com for a while

[readme] Update Travis CI badge and link url

---

Dockerfile

Did some basic tests, besides old versions like node.js v12 will need python 2 to build from source, the other part looks good.

[Dockerfile] Update base image from Ubuntu 20.04 to 22.04, cc #2877

---

nvm.sh
test/fast/Unit tests/nvm_find_project_dir
test/fast/Unit tests/nvm_find_up

This PR fixes an issue where `pwd` can return `"."` due to insufficient permissions, e.g. when switching users using the `su` command, which causes an infinite loop in the `nvm_find_project_dir` and `nvm_find_up` functions.

Fix directory traversal when workdir path is not readable

---

README.md

fix: shellcheck errors

---

nvm-exec

the `nvm.sh` file assigns and exports an `NVM_CD_FLAGS` variable if it
was sourced from a zsh shell. the fact that it's exported means that
it'll be assigned in all child processes, including the `nvm-exec`
script, which uses bash as the interpreter.
Bash's `cd` command doesn't have a `-q` flag, so if the `NVM_CD_FLAGS`
is assigned `-q`, the script will error out and incorrectly claim that
the node version isn't installed.
this also manifests itself in the `nvm exec` command.
Example:
```console
$ nvm exec 16.14.0 npm --version
Running node v16.14.0 (npm v8.3.1)
/Users/<ME>/.nvm/nvm.sh: line 28: cd: -q: invalid option
cd: usage: cd [-L|[-P [-e]] [-@]] [dir]
both the tree and the node path are required
N/A: version "v16.14.0 -> N/A" is not yet installed.
You need to run "nvm install …
```

[Fix] 'nvm exec' no longer prints error about '-q' being an invalid option

---

nvm.sh
test/fast/Unit tests/nvm_get_arch
test/mocks/uname_linux_armv8l

Fixes https://github.com/nvm-sh/nvm/issues/3035
I wasn't sure what would be the best solution. Right now, if `NVM_ARCH` is `armv8l`, it falls back to `armv7l` since `ARMv8` is backward compatible with `ARMv7`.
I think other approaches are
- Changing `aarch64) NVM_ARCH="arm64" ;;` pattern to  `aarch64 | armv8l) NVM_ARCH="arm64" ;;`. That way it would step into the following code block and also fall back to `armv7l`.
```
if [ "$(uname)" = "Linux" ] \
&& ( [ "${NVM_ARCH}" = arm64 ] || [ "${NVM_ARCH}" = armv8l ] ) \
&& [ "$(command od -An -t x1 -j 4 -N 1 "/sbin/init" 2>/dev/null)" = ' 01' ]\
; then
NVM_ARCH=armv7l
HOST_ARCH=armv7l
fi
```
- Instead of falling back to `armv7l`, create another if block to use `arm64`, something like
```
if [ "$(uname)" = "Linux" ] \
&& [ "${NVM_ARCH}" = armv8l ] …
```

[Fix]: Fix NodeJS download link for armv8l

---

README.md

I had to dig into https://github.com/nvm-sh/nvm/issues/2410 to learn about the `PROFILE=/dev/null` technique to install without appending to my shell config. Figured this note would be good to add in the main installation docs.
Also added a note on how to do this as a one-liner which was not obvious for me.

Add instructions on how to install without editing shell config

---

README.md

**PR Summary**:
The PR contains a fix to typo found it the `README.md` file. The `resolve.conf` file should be `resolv.conf`.

[readme] fix typo in resolv.conf filename

---

README.md

Made a tool, [`nvshim`](https://github.com/iamogbz/nvshim), for shimming `node` binaries using `nvm`. Useful as an option for people that do not want to add auto loading script to their shell.
Unsure of the community rules about self promotion, just thought to share since it's been working for myself and a couple others.

[readme] add `nvshim` tool alongside `avn`

---

README.md

In numerous blog posts regarding the configuration of the default nodejs version using nvm, the following command is often cited:
```sh
nvm alias default node
```
While this command might work in some cases (as `node` will point to the latest version installed on your system), it might not behave as intended if you want to default to a specific version of Node.js. 
This command is actually referring to the [Set default node version](https://github.com/nvm-sh/nvm/blob/c6e35bae08ac4ea329c36aaaaf951b32a4612d80/README.md#set-default-node-version) section in the nvm's README. It's crucial to note that the instructions suggest setting a specific node version of your choosing, rather than using the generic `node`. 
So if you're aiming to set a particular version (for example, 14.15.1) as your …

[readme] add examples of setting specific versions as default

---

nvm.sh
test/fast/Unit tests/nvm_strip_path

Preserve leading & trailing colons in awk invocation.

[Fix] `nvm_strip_path`: Preserve leading/trailing colons

---

Dockerfile

Bug: missing `/home`
```
> [18/24] RUN chown nvm:nvm -R "home/nvm/.nvm":
0.467 chown: cannot access 'home/nvm/.nvm': No such file or directory
------
dockerfile:90

[Dockerfile] [Fix] add missing leading slash in path

---

Dockerfile

Looks like it's no longer needed. All commented by default. Can verify by the command below:
```
$ for ver in 16.04 18.04 20.04 22.04; do docker run --rm -it ubuntu:$ver sh -c 'grep deb-src /etc/apt/sources.list'; echo; done
```

[Dockerfile] Remove apt src disabling, no longer needed

---

README.md

The current documentation leads to confusion. The command nvm install will respect .nvmrc, install the correct version, and automatically switch to it. This is not properly communicated to the end user. The github discussion below is an example.
https://github.com/ubccsss/ubccsss.org/pull/503
I added what nvm install will do in the presence of an .nvmrc file, to clear up future confessions.

[readme] add section on bare `nvm install`

---

.github/workflows/windows-npm.yml
nvm.sh
test/fast/Unit tests/nvm_get_arch_unofficial

@ljharb I have updated, nvm_get_arch to return proper value for alpine, please let me know if that would work.

[Fix] `nvm_get_arch`: proper value for alpine linux

---

README.md

This PR fixes the level of a few headings in the README file.
"Restoring PATH", "Set default node version", and "Use a mirror of node binaries" should not be subsections under the "Setting Custom Colors" section. The change will make the TOC easier to scan for readers.

[readme] fix level of headings

---

README.md

I was having trouble installing a new version of Node using the `--latest-npm` flag.  After reading the help message again, I noticed the following:
```
The following optional arguments, if provided, must appear directly after `nvm install`
```
All of the `nvm install` examples in the README currently put the arguments after the version.  This change should reduce confusion and better align with the intended usage.
Note: The `--reinstall-packages-from` flag works just fine when put after the version, but `--latest-npm` (and possibly others), need to come directly after `nvm install`.

[readme] rearrange install args

---

README.md

Fix typo in WSL section of README

---

.github/workflows/latest-npm.yml
.github/workflows/lint.yml
.github/workflows/rebase.yml
.github/workflows/release.yml
.github/workflows/require-allow-edits.yml
.github/workflows/shellcheck.yml
.github/workflows/tests.yml
.github/workflows/toc.yml

Resolve deprecation warnings, see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

[actions] update action versions to use node 20

---

README.md

`nvm unload` will unset NVM_DIR. So gotta save NVM_DIR first.

[readme] Fix uninstall instructions

---

README.md

`nvm unload` will unset NVM_DIR. So gotta save NVM_DIR first.

Fix README.md uninstall instructions

---

Makefile
README.md
nvm.sh
test/fast/Running 'nvm unload' should unset all function and variables
test/fast/Unit tests/nvm_download

A simple POC to build from, but wanted to open for feedback on #3366

Auth support for NVM_AUTH_HEADER env var

---

nvm.sh

Fix issue with the color codes in the nvm help text where short shell aliases would display an inline error in the nvm help text.
Given a zsh alias such as:
```sh
alias -g C='| clipcopy'
```
This would cause an issue with the `nvm --help` text, where the colour code function would have an unquoted 'C' and therefore print an error to the console and silently continue. I have attached a screenshot of what it looks like with this update and what it looks like before

[patch] Fix issue where zsh global aliases break nvm help

---

.dockerignore
.gitignore
nvm.sh
test/fast/Unit tests/Running 'nvm install --save' works as expected'
test/fast/Unit tests/Running 'nvm use --save' works with a .nvmrc in the parent dir
test/fast/Unit tests/Running 'nvm use --silent --save' doesn't output anything
test/fast/Unit tests/Running 'nvm use -w' works as expected'
test/fast/Unit tests/nvm_write_nvmrc

In this PR I've:
- added a `--save` option as per #2849 
- implemented it for both `nvm use` and `nvm install` (which actually just carries over the option)
- manually tested it in `bash`, `sh` and `zsh`
- written one test, however I can't get the slow tests to run on my system so hopefully it runs okay :crossed_fingers: (if someone would be able to check that, that'd be great)
Fixes #2849

[New] `nvm use`/`nvm install`: add `--save` option

---

nvm.sh
test/slow/nvm use/Running 'nvm use lts' shows actionable error

When using the command `nvm use lts`, users encounter the following error message:
> N/A: version "lts" is not yet installed.
You need to run `nvm install lts` to install and use it.
However, the LTS version is already installed on the system, and the command nvm use --lts works correctly. This inconsistency causes confusion and inconvenience for users who expect nvm use lts to function as intended.
The issue was identified in the `nvm_remote_version` function within the `nvm.sh` script. The function did not correctly handle the `lts` alias, leading to the error message.
To resolve this, I modified the `nvm_remote_version` function to include a case for the `lts` alias. The updated function now correctly maps the `lts` alias to the latest LTS version.
- …

[patch] give a more helpful message when `lts` alias is mistakenly used

---

CONTRIBUTING.md

imo this shouldn‘t be necessary, as it should be implied by the act of making a PR.
Following the example in https://github.com/expressjs/express/pull/6048
See https://github.com/openjs-foundation/project-status/issues/2

[meta] add DCO

---

.github/workflows/tests.yml
install.sh
test/install_script/nvm_detect_profile

I just saw that you merged it and your message, it seems that the urchin tests aren't run until a commit is pushed - which is why we didn't catch the test failing. (So I added that as a separate PR #3466 - under the assumption that if you merge that first, we can run the test on this PR to ensure it fixes the issue)
This should address the failing tests. I missed the line for an unset $SHELL variable in `install.sh` - the rest of the PR is unsetting `$ZDOTDIR` for the other shells test (they will fail if it remains set). Local testing verifies this passes the urchin tests, though.

[Fix] `install.sh`: fix failing install tests from #3458

---

README.md

fnm has been renamed to nvm.fish and the repo has been transferred to https://github.com/jorgebucaran.

[readme] fnm -> nvm.fish

---

README.md

`avn` is archived ([see repo](https://github.com/wbyoung/avn)) and should probably no longer be recommended by nvm.

[readme] remove `avn` from readme

---

Dockerfile
README.md

It's common to install node in docker, and using NVM is quite helpful in this regard. Installing and using NVM isn't always. straightforward.
Make it easier for users to setup nvm in docker by droppin' some docs.
Ref: https://stackoverflow.com/questions/25899912/how-to-install-nvm-in-docker

[readme] add docker tips

---

README.md

* Changes the suggested shell when running the install script to $SHELL
which will return the default shell.
* Adds a note for how to fix the issue when the install script is not
updating the correct profile file.
* Reorders the list of profile files to match the order of files the install script looks for.
NOTES ON CHANGES:
This documentation change is to help users who are finding that the install script is not updating the correct shell profile file. `$SHELL` will return the path to the default shell used, which will set the environment variables used by the install script to decide which profile file to update. There are reports of users not sure why their preferred profile file is not being updated here https://github.com/nvm-sh/nvm/issues/2196.
I suspect that many of these are from …

[readme] Update shell profile file install notes

---

README.md

Following the instructions, I perceived that a possible and useful piece of information was missing.
I added to perform a reload of the configuration after the changes.

[readme] add note about reloading zshrc after editing

---

README.md

Add a subsection to `README.md` about using zsh-nvm's `NVM_AUTO_USE` option to automatically detect and use `.nvmrc` files; the zsh-nvm plugin is mentioned already in the README (in the installation section).

[readme] note zsh-nvm's AUTO_USE option

---

README.md

Fix the --no-use example
When i first try to use the --no-use flag i thought I had to write `[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh --no-use"` because of the example (see the missed placed double quote)

[readme] fix `--no-use` example

---

nvm.sh

`nvm_version_greater 20.17.0 v22.14.0` exits with code 3 and nvm thinks node version is `NVM_IS_20_5_OR_ABOVE` thinking npm@10 is the latest compatible with 22.14.0.
Switch to `nvm_version_greater_than_or_equal_to` and for consistency change `NVM_IS_20_17_or_ABOVE` variable to uppercase.
Before patch
```
$ nvm version
v22.14.0
$ nvm install-latest-npm
Attempting to upgrade to the latest working version of npm...
* `npm` `v10.x` is the last version that works on `node` `< v20.17`, `v21`, or `v22.0` - `v22.8`
```
After patch
```
$ nvm version
v22.14.0
$ nvm install-latest-npm
Attempting to upgrade to the latest working version of npm...
* Installing latest `npm`; if this does not work on your node version, please report a bug!
```

Fix node version detection in nvm_install_latest_npm
