README.markdown
Not entirely sure this is the best place for this but it was the best I could find.
=> Adding iojs to README.

README.markdown
=> add iojs mirror to README

nvm.sh
This saves a few milliseconds.
=> Combine sed and grep commands

nvm.sh
The word "copying" is a bit misdirected, imo.
=> nvm.sh: s/copying/reinstalling/

install.sh
Fixes #826
This reverts commit b4151e1446f36d534a8a98e6876d293e05317173.
=> Revert "Source the nvm.sh file"

nvm.sh
=> Replace backticks with $() command substitution

README.markdown
Based on @ljharb's [comment](https://github.com/wbyoung/avn/issues/29#issuecomment-153446871).
=> Updated docs for alias default

README.markdown
Nodist is a similar CLI interface providing similar functionality. Nodist also recently added a Windows install wizard.
=> Add another Windows alternative.

README.markdown
Seems to be abandoned:
- https://github.com/hakobera/nvmw/issues/67
- https://github.com/hakobera/nvmw/issues/66
- https://github.com/hakobera/nvmw/issues/69
=> del nvmw link

README.markdown
Also adds a snippet for zsh user to auto-issue `nvm use` when entering a
directory.
=> Add section about "Deeper shell integration"

README.markdown
Also, clarified the existing shell integration intro text.
=> Add link to avn

README.markdown
=> Adds fast-nvm-fish to README

README.markdown
As per #995, this PR adds an example `.nvmrc` to the README.
=> Add an example .nvmrc

README.markdown
Also modified the order of the items alphabetically.
=> Add fin https://github.com/fisherman/fin.

README.markdown
=> Added section about verifying nvm install

README.markdown
Revert to default node version when leaving a .nvmrc directory (ie when entering a directory with no .nvmrc when version != default).
=> Improve zsh script in README

README.markdown
Minor fixes:
- fix typo, "Simple" -> "Simply"
- improve consistency of how colons are used (i.e., before all code blocks)
Thanks for all your work! nvm is great!
=> [docs] Update README.md

README.markdown
Will make the doc easier to read.
=> use sh syntax highlight in README.markdown

README.markdown
As discussed in https://github.com/creationix/nvm/issues/1153
=> Link to zsh-nvm in readme

install.sh
As discussed in https://github.com/creationix/nvm/issues/1177
=> Installation improvements

.travis.yml
This is really helpful for debugging tests that pass locally but fail on Travis.
=> Print shell version on Travis

README.markdown
Add menu for the first two level titles for better readability
=> add a menu for readme for easier readability

nvm.sh
=> Fix indent at L2672

bash_completion
retab hard-tab to 2 spaces as other indents in nvm
=> fix/retab indent in bash_completion [no-ci]

README.markdown
Thanks to @ljharb for applying for it!
Related to: #1395 
Preview: https://github.com/ypid/nvm/tree/add/cii_badge#node-version-manager---
=> Add CII best practices badge

nvm.sh, test/fast/Unit tests/nvm_get_mirror
=> [Fix] stop setting mirror env vars unnecessarily

README.markdown
I update title of #900 to be more precisely and correct.
=> [Docs] Update issue #900 title in README.markdown

.travis.yml
ref: afba4e08fd18c73907025850239a0adf4104c611
=> [Tests] Comment out ksh dependency installation, cc #574

LICENSE.md, README.markdown
It's been more than a year since https://github.com/creationix/nvm/commit/896199facc8ea24730a1519b7392ccc42a353cd5
=> Update README.markdown and LICENSE.md

install.sh
Should make the code easier to read.
=> [Refactor] Improve profile detection in install script

README.markdown
Correct two double [tab] and try to improve its readability
=> [Docs] Improve nvm usage examples

.travis.yml
Should use `before_cache` instead of `after_success`
=> [Tests] Fix cache for WITHOUT_CURL tests in Travis

nvm.sh
=> Enhance nvm debug with more tools info

README.md
=> Improve git installation instructions

.travis.yml
Sorry that I forgot to clean it up in #1619(didn't recall that ghc is for ShellCheck installation), didn't mean to earn another PR or commit :)
=> [Cleanup] Remove ghc related things in .travis.yml, cc #1619

LICENSE.md, README.md
=> [copyright] update to 2018

README.md
=> [Docs] Add reminder that NVM_DIR should not contain trailing slash

nvm.sh
This could help debug in nested shell.
=> [New] Print $SHLVL in `nvm debug`

nvm.sh
No matter what's the result of the condition here, the path is always the same.
=> Remove duplicate code in nvm_npm_global_modules()

CONTRIBUTING.md, Makefile, README.md, ROADMAP.md, test/install_script/nvm_detect_profile, test/mocks/uname_osx_amd64, test/mocks/uname_osx_x86
=> [Fix] Correct most of the wrong indentation

.github/ISSUE_TEMPLATE.md, README.md
=> [Docs] Fix some typos

README.md
=> removed global install on README.md. closes #1773

README.md
This adds instructions how to uninstall nvm.
=> Add removal instructions to README.md

README.md
=> [Doc] Add macOS install script note about Git

README.md
Address #1900 
Not sure if this is the best place to shove this in, but I don't see a better alternative without drastically reordering the README to flow better in terms of how folks might use the tool the first time.
=> Update README with instructions for installing specific version.

README.md
=> [Docs] improve instructions for manual install

README.md
=> [docs] update README to fix docker run command flag order

nvm.sh
=> Allow zsh users to have the nomatch option set

nvm.sh
Just notice some exceptions on macOS and Alpine linux(busybox based binutils), this should help catch them.
=> [Fix] Enhance nvm debug for different environments

nvm.sh
- Add `{ }` to variable reference
- Fix indentation of `case` and some multi-line commands
- Put `;` do and `; then` on the same line as the `while`, `for` or `if`.
- Remove `;` of single line commands
References:
- https://google.github.io/styleguide/shell.xml
- https://github.com/mvdan/sh
The `sh`/`shfmt` tool can't be integrated with CI yet as there are some styles can't be customized and the changes are too many, so just use it as a reference, helper currently, the fixes are still made by myself.
=> [Refactor] `nvm.sh`: make coding style more consistent

README.md
=> Update README: sync node release schedule url

README.md, nvm.sh
Greets
For better and more readable plus show version in help output 
I think it's more productive like every other program or package like gcc or clang when we command help and get version in that
Plus +
I wanted to colorize the number of version in output but I didn't succeed in it
If you can COMPLETE it that I appreciate that
And
For README after I saw a commit that add update to it but for such a big amount of question that in my work office asked me about how to update NVM so I just bold and change the title to better understanding 
Thanks for great shell script tool
Very needed
=> Better help document

README.md
=> Add note about what version of node new shells run with.

README.md
There's a lot of old info around the interwebs.
Much stating nvm doesn't work in WSL.
=> Updated note about Windows

README.md
I was installing nvm and got confused while following the install instructions. I want to make it easier for future users ^_^.
Also, the script didn't add the profile snippet to my `.zshrc` file, and I had to do that manually. Probably because I have both .bashrc and .zshrc lying around. 
* I made changes to the install instructions I believe will make it easier to read. 
* Added instructions to add the profile snippet manually to the documentation.
=> Clarify install instructions and add one trouble shooting suggestion

test/fast/Unit tests/nvm_get_default_packages
Solves part of https://github.com/nvm-sh/nvm/issues/2181
=> Fix bug in test nvm_get_default_packages

README.md
=> [readme] Mention problem with windows cmd echo

README.md
Edited the LTS upgrade scenario command to fix the issue discussed over here
https://github.com/nvm-sh/nvm/pull/2271
=> Update README.md for LTS upgrade

Dockerfile
=> Update ShellCheck download URL in Dockerfile

Dockerfile
Should be done in #2187 #2305 but missed, sorry.
=> [Dockerfile] Clean up dated comment

bash_completion
Fixes #2325 by changing the sequence of steps
=> [Fix]: Fixes errors with compinit and bashcompinit

nvm.sh, test/sourcing/Sourcing nvm.sh global alias bug
=> Fix error with zsh aliases in nvm_print_color_code

README.md
Fixed shell command typo on --latest-npm example
=> [readme] quote asterisk in shell command on `--latest-npm` example

README.md
Linux troubleshooting: 
Troubleshoot without closing the current shell.
=> Troubleshoot without closing the current shell.

README.md
Adding in missing s so the source command can be run correctly
=> Update source command to include s in zsh

README.md
=> fix: typo in README.md regarding docker image base in Dockerfile

.github/workflows/windows-npm.yml, install.sh
=> [Fix] `install`: fix method=script install condition

README.md
I got a chance to fix my [complaints](https://github.com/nvm-sh/nvm/pull/2653#issuecomment-982219834) about the previous M1 docs. There were a lot of unnecessary details included and some misleading comments. I think this simplifies the instructions without removing any important pieces of information.
=> [readme] clarify instructions for running Node on M1 Mac

README.md, nvm.sh, test/slow/nvm_get_latest/nvm_get_latest, test/slow/nvm_get_latest/nvm_get_latest failed redirect
Checked the links, skipping the redirect HTTP => HTTPS this way 0:-)
(Also: Hi again 0:-))
=> README.md: HTTP => HTTPS

CODE_OF_CONDUCT.md
Incorporates the changes of CoC from the contributor covenant to version 2.1.
=> Update CODE_OF_CONDUCT to current version.

README.md
Add note about creating .bashrc file *as well as* .bash_profile.
My problem was that I didn't have EITHER file, and hopefully the notes will help someone else reading the docs.
=> [Docs] Add note about creating `.bashrc` file *as well as* `.bash_profile`

Dockerfile
=> [Dockerfile] Update base image from Ubuntu 18.04 to 20.04

README.md
hopefully this fixes the indent issue for the test I was failing in my last PR
closes #2958
=> added WSL Troubleshooting and provided a solution to a common problem (fixed typos)

CONTRIBUTING.md
Merges older contributors.md with newer standards. Let me know if anything needs reworking. I've removed the dev install instructions and linked to the readme as that includes all the tips and tricks particular to `nvm`.
=> Improve contributors documentation

CONTRIBUTING.md
Fixes https://github.com/nvm-sh/nvm/issues/3104
=> [Docs] Remove unavailable testing script

README.md
Use GitHub flavored markdown for dark mode
=> [readme] Update logo header

README.md
Just wanted to be of help and fix a simple missing parenthesis :)
=> [readme] missing parenthesis

README.md
Fix typos and update M1 to Apple silicon because of M2 and M3
=> [readme] update M1 to “Apple Silicon” because of M2 and M3; fix typos

README.md
add the last step to uninstall  nvm
=> [Docs] add `nvm unload` to uninstall nvm instructions

.github/workflows/tests.yml
To prevent future RPs from looking good and then failing urchin tests after merge
=> [actions] run urchin tests on pull request
